### ISSUE TITLE
Feature: Add the "very_good_analysis" package to the project

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#100]
### Description

I think we should add the [very_good_analysis](https://pub.dev/packages/very_good_analysis) package to our project as it can help us in:-

- **Improving Code Quality**: It will help us to catch errors and potential problems early on in the development process. This will lead to a more robust and reliable codebase. 
- **Improving the Performance**: It'll help us to identify and fix the performance bottlenecks. This will lead to a faster and more responsive app. 
- **Improving the Accessibility**: It'll help us to ensure that our app is accessible to all users, including those with disabilities. This will make our app more inclusive and user-friendly. 
- **Improving the Security**: It'll help us to identify and fix the security vulnerabilities. This will make our app more secure. 

Concluding this, I think we should add the `very_good_analysis` package to our project. It can help us to improve the quality, performance, accessibility, and security of the app. 

_I would like to work on this issue, so please assign it to me._

**Comment by MarkisDev** [comment]
Assigning to you.

**Comment by superiorsd10** [comment]
Hey @MarkisDev 👋
I've tried adding the `very_good_analysis` package to our project, but it's flagging tons of type-casting-related errors. So I think it would be better to add good-practice linter rules by ourselves instead of relying on that package. 

I'm thinking of adding the linter rules to the `analysis_options.yaml` file. 

What do you think?

**Comment by MarkisDev** [comment]
Sure, go for it.
