### ISSUE TITLE
Feature: Change the checkbox fill color

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#101]
### Description

The current `CheckBox fillColor` looks weird for both light and dark modes. When the user checks, only the opacity of the color increases, and it affects the UX of the app.  

I think we should change the `fillColor` for both light and dark modes to increase the UX of the app. 

I've provided the screenshots of before and after of this feature implementation. Please look into it. 

_I would like to work on this issue, so please assign it to me._

### Dark Mode

**Before**
<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/72dd3b49-552a-4a80-b219-6d446a8ec98a" width="250" height="550">

**After**
<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/f7e188e7-adca-4f97-96ad-77f724745a94" width="250" height="550">

---

### Light Mode

**Before**
<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/f96cd408-e17e-4e9d-b371-048023447908" width="250" height="550">

**After**
<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/8951ed79-e8f1-47fe-9ee6-b5408679444a" width="250" height="550">

---

**Comment by MarkisDev** [comment]
Ah, I almost didn't notice this. Assigning the PR to you!
