### ISSUE TITLE
Feature: Turn autofocus on, and apply hint text to weather API textfield

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#102]
### Description

Currently, when the user wants to add/update their Weather API key, they have to tap on that particular tile in the `SettingsView`. If they want to add their API key (which means they haven't added it yet), then they don't see anything inside the `TextField`, and to enter, they have to tap on the `TextField`. 

So, I think we should apply some `hintText` to the `TextField` of the Weather API key. It could be `Enter API Key...`. 

Also, the `autofocus` should be turned on so that they don't have to tap onto the `TextField` to enter their API Key. It'll make things easier for them comparatively. 

_I would like to work on this issue, so please assign it to me._

### Screenshots

<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/76898680-4551-4303-8ffc-009d077af679" width="250" height="550">

**Comment by MarkisDev** [comment]
Sure, go ahead with this. Assigning the issue to you.
