### ISSUE TITLE
Feature: Show CircularProgressIndicator when the user taps on Add/Update button on Weather API Key dialog

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#103]
### Description

Currently, when the user taps on the `Add/Update` button to add or update their Weather API Key, the success dialog is shown after some seconds due to all the processes happening in the background. 

But, the current `Add/Update` dialog remains static, and it can make the user think about whether they have tapped the button or not. So I think that we should show a `CircularProgressIndicator` while the process is happening indicating that the user should wait for a little bit. 

It will certainly improve the UX of the app. 

_I would like to work on this issue, so please assign it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/f30b335e-c9d8-4a5f-804a-9686839631b8

**Comment by MarkisDev** [comment]
This should help mask that delay, sounds like a good idea.
