### ISSUE TITLE
Docs: Add the docs regarding the architecture of the app

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#109]
### Description

As the project continues to evolve, it's crucial to have comprehensive documentation that provides insights into the app's architecture. This documentation will not only serve as a valuable resource for the current contributors but also for newcomers who want to understand how the app is structured and organized.

I'm planning to add these key points to the documentation:-

- Overview of the App's High-Level Architecture
- Directory Structure
- Key Modules and Components
- Data Flow
- Technology Stack
- Code Patterns and Best Practices
- Development Guidelines

Additionally, I'll be including visual diagrams, and links to relevant resources to enhance the comprehensibility of the documentation. 

_I would like to work on this issue, so please assign it to me._

**Comment by MarkisDev** [comment]
Hey, yeah. I have to get this done as well. The reason I've delayed it a bit is that I'm reworking a core part of the application which will probably change the data flow and architecture, didn't want to redo docs because of this change. 

However, some will still remain the same. Let's discuss over Slack on what we can include for now.

**Comment by superiorsd10** [comment]
> Hey, yeah. I have to get this done as well. The reason I've delayed it a bit is that I'm reworking a core part of the application which will probably change the data flow and architecture, didn't want to redo docs because of this change.
> 
> However, some will still remain the same. Let's discuss over Slack on what we can include for now.

Sounds good! Let's discuss it.
