### ISSUE TITLE
Requesting Permissions 

### ISSUE THREAD

**Issue by MarkisDev** [CCExtractor/ultimate_alarm_clock#11]
Right now, the app directly asks for the necessary permissions (location, camera, display over apps etc.) without any context as to why it needs it.

We need to make a popup (maybe with a dialog) and explain why we need it then redirect.

**Comment by rishi115** [comment]
Can I work on this issue ?

**Comment by MarkisDev** [comment]
Sure thing. 

Most of the functionality to check if the permission is enabled and directly opening the necessary settings page on phone is done, you just need to make a "Middleman" to ensure the user knows they're going to be redirected to settings.

If you have follow up questions, feel free to ask me :)

**Comment by Kavan2003** [comment]
I want to work on this issue

**Comment by MarkisDev** [comment]
@Kavan2003 It's just been a day since I've assigned it to @rishi115. 

If @rishi115 is no longer working on it, I'm happy to assign it to you!

Meanwhile, feel free to take a look around the codebase and raise any new issues you find :)

**Comment by rishi115** [comment]
I  am working on this issue:)




https://github.com/CCExtractor/ultimate_alarm_clock/assets/69479714/ab473221-846a-477b-8080-25f5d93a85d6
pls check ur slack dm @MarkisDev

**Comment by rishi115** [comment]
pls check my #22 PR.

**Comment by MarkisDev** [comment]
Fixed with #26
