### ISSUE TITLE
Bug: Value and background color of CircularProgressIndicator are same

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#110]
### Description

The `valueColor` and the `backgroundColor` of the `CircularProgressIndicator` are the same. As a result, the loading effect of the `CircularProgressIndicator` diminishes. Due to the color being the same, it looks like it's static, and nothing is loading. 

I think that we should change the `backgroundColor` of the `CircularProgressIndicator`. 

_I would like to work on this issue, so please assign it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/ada5aaff-7523-4fb6-a663-5fd9ca186237

**Comment by tavkeer** [comment]
i will do this?

**Comment by MarkisDev** [comment]
Ah, since @tavkeer already did it I'll take a look at his PR.

**Comment by tavkeer** [comment]
@MarkisDev 
https://github.com/CCExtractor/ultimate_alarm_clock/assets/105163810/787b3e84-1e67-4977-ae9a-9d014b0518ad

**Comment by tavkeer** [comment]
@MarkisDev 
here is the video explaining the change!

**Comment by MarkisDev** [comment]
Fixed with #112
