### ISSUE TITLE
In preview alarm, the Exit Preview button color and text Does not change according to the theme controller(Error occurs when dark Mode is Enables).

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#118]
### Description

It is very obvious that one should preview their alarm exactly the same and it will match what they see when the alarm rings in real.
Could you please assign this issue to me?

### Screenshots

when the alarm rings:-
![Screenshot_2023-10-22-20-56-08-213_com example ultimate_alarm_clock](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/d11de703-c2a8-47ce-bd2f-9dc801e16340)

Before fixes:-
![Screenshot_2023-10-22-20-36-58-777_com example ultimate_alarm_clock](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/9af3b4a1-4265-429c-891e-4dbdea3787fa)
![Screenshot_2023-10-22-20-50-08-864_com example ultimate_alarm_clock](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/8ecdd510-6f6c-456d-b548-0e970c3226bc)

After fixes:-
![Screenshot_2023-10-22-20-51-47-053_com example ultimate_alarm_clock](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/e6c57eb9-1cfb-4d32-816b-ef45f9e7cd61)
![Screenshot_2023-10-22-20-54-05-409_com example ultimate_alarm_clock](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/c74959b3-bf94-4aaf-8a4d-82a58612e2b0)

**Comment by MarkisDev** [comment]
I can see how this might have seemed unusual - there seems to have been a bug where the "Dismiss" button didn't show up in preview. The idea was to allow users to preview the challenges to Dimiss as well.

In such a situation, we needed a different colored Exit preview button since you couldn't quit the ringing alarm screen without clearing the challenges.

I've fixed that with the latest PR - however, there's an issue with the Exit Preview button's color not matching the theme. I'll leave that issue to you if you like!

**Comment by sameermansoori1** [comment]
> I can see how this might have seemed unusual - there seems to have been a bug where the "Dismiss" button didn't show up in preview. The idea was to allow users to preview the challenges to Dimiss as well.
> 
> In such a situation, we needed a different colored Exit preview button since you couldn't quit the ringing alarm screen without clearing the challenges.
> 
> I've fixed that with the latest PR - however, there's an issue with the Exit Preview button's color not matching the theme. I'll leave that issue to you if you like!

Ok, @MarkisDev.
I am ready to work on that.
If you have some color Ideas please tell

**Comment by sameermansoori1** [comment]
Have a look @MarkisDev 
![exa1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/ec18b916-ded0-4541-a28d-55514610af75)
![exa2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/d1f82fc3-5416-4e27-9f91-6f5f3017f76a)

**Comment by sameermansoori1** [comment]
@MarkisDev Another one, have a look
![pr2 1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/41e27c05-8b45-41b6-8a0b-480f033fa153)
![pr2 2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/0431de0c-b1b0-4d16-90b9-07fd1c2fa808)

**Comment by MarkisDev** [comment]
Ah, I meant that the exit preview button's color wasn't matching with whatever was defined in `ThemeController`. It probably has to do with something not updating the state once the current theme (light/dark) is fetched. 

I'd like to keep it the same color (grey) itself. We just need to fix that!

**Comment by sameermansoori1** [comment]
> Ah, I meant that the exit preview button's color wasn't matching with whatever was defined in `ThemeController`. It probably has to do with something not updating the state once the current theme (light/dark) is fetched.
> 
> I'd like to keep it the same color (grey) itself. We just need to fix that!

oh got it. 
I will fix it soon
