### ISSUE TITLE
error screen while changing theme 

### ISSUE THREAD

**Issue by RunTerror** [CCExtractor/ultimate_alarm_clock#119]
### Description

when we again change the theme after changing it once, then error screen shows up.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/113206442/2e470f3b-9e0c-40fe-82cd-0d1d4b111c4d

Please assign me this issue I have find the problem.

**Comment by MarkisDev** [comment]
That's quite unusual. I'll assign this to you, please give it a shot. 

If you get stuck somewhere, feel free to ask me :)
