### ISSUE TITLE
Done button added while editing dates of an alarm

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#12]
Issue : In the old UI user have to click anywhere out of the dialogue box but now I have added an 'Done' button to make UI looks simpler

[done button.webm](https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/daf4648a-536d-4b9f-a25f-7c02453ab9b8)

**Comment by BrawlerXull** [comment]
Solved by #13 @MarkisDev

**Comment by MarkisDev** [comment]
This doesn't really look like an issue to me. 

Could be a UI enhancement though, but if you want to take this up you'll have to ensure every single dialog has the button to ensure UI consistency :)

**Comment by BrawlerXull** [comment]
I'll implement same button to everybox and let you know

**Comment by BrawlerXull** [comment]
> This doesn't really look like an issue to me.
> 
> Could be a UI enhancement though, but if you want to take this up you'll have to ensure every single dialog has the button to ensure UI consistency :)
> 
> Make sure the button's color is consistent with the theme as well.

check #16
