### ISSUE TITLE
updating enable/disable keyword according to theme

### ISSUE THREAD

**Issue by RunTerror** [CCExtractor/ultimate_alarm_clock#120]
### Description

we can use "disable light mode" when the switch is on this will improve user experience.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/113206442/66315bd1-a9f4-4b75-83a9-c5cd7542e915

**Comment by tavkeer** [comment]
Can I work on this???

**Comment by sameermansoori1** [comment]
> solved it

This is not the right way of doing things @DhruvSethi7, You should first ask @MarkisDev to assign this issue to you.
In my opinion or I think @MarkisDev has the same thinking as the one who raised the issue, Firstly the chance is given to him/her only, In this @RunTerror is the one.

**Comment by superiorsd10** [comment]
Hello @RunTerror 👋
I think this will lead to more confusion among the users. The title of the list tile should be static. When the switch is off, it's showing `Enable Light Mode`, and when it's on you're suggesting to change it to `Disable Light Mode`, but as the switch is on, and the title is `Disable Light Mode`, it indicates to dark mode, but light mode is on.

**Comment by RunTerror** [comment]
@superiorsd10 you are also right but i think updating text will be more right.

**Comment by MarkisDev** [comment]
I agree with @superiorsd10. Changing the text will just lead to more confusion.

**Comment by MarkisDev** [comment]
@DhruvSethi7 I'm glad you're enthusiastic and contributing to the project! Please continue doing so but as @sameermansoori1 let's try and keep it organized in order to avoid confusion :)

Keep up the good work guys! Super happy to see so many contributors!

**Comment by DhruvSethi7** [comment]
I am really sorry , i am new to open source ,i dont know about this things.

**Comment by sameermansoori1** [comment]
> I am really sorry , i am new to open source ,i dont know about this things.

@DhruvSethi7, I think you should take a look at this. I believe it will clear up any doubts you have.
https://github.com/CCExtractor/ultimate_alarm_clock/pull/88#issuecomment-1740227491
and don't forget to thank @superiorsd10

**Comment by DhruvSethi7** [comment]
Thanks  @sameermansoori1 for recommendation and @superiorsd10 for the valuable information

**Comment by superiorsd10** [comment]
> Thanks @sameermansoori1 for recommendation and @superiorsd10 for the valuable information

No worries, man :)
