### ISSUE TITLE
Feature: Option to choose time by adding it through soft keyboard.

### ISSUE THREAD

**Issue by SATVIKSH** [CCExtractor/ultimate_alarm_clock#124]
### Description

The only available option to choose time is by scrolling the digits available for hours ,minutes and period of the day. An alternate option for selecting time using soft keys by directly entering digits might provide a better user experience. I can work on this issue if it is assigned to me.

**Comment by MarkisDev** [comment]
It does sound like a good idea. Please just ensure that it sticks to the theme of the app though!
