### ISSUE TITLE
Feature: Implementing Custom Error Screen

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#133]
### Description

Currently, if any error/exception is thrown, a red screen appears in the UI. It's not good at all in terms of the user experience. So I think we should implement a custom error screen that shows the user what can be the issue.

_I would like to work on this, so please assign it to me._

### Screenshots

_No Response_

**Comment by MarkisDev** [comment]
I've assigned this to you.
