### ISSUE TITLE
Feature: Modal Functionality for Info Icon on Add Alarm Screen

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/ultimate_alarm_clock#135]
## Description
- At present, within the interface, distinct modals are utilized for various information categories such as Screen Activity, Weather Condition, Location Bases, etc., each represented by an (i) icon.

## Problem: 
- The current implementation involves separate code snippets for each modal, leading to a reduction in code reusability, readability, and maintainability.

## Solution:
- To address this issue, I've introduced a dedicated function named showModal within the utilities class/folder. This function streamlines the process by allowing the input of parameters such as title, description, relevant icon, and theme data.
- I have completed the implementation of the function and have successfully incorporated it into the codebase.

Please assign the issue to me.

### Screenshots

![modal](https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/e6846b45-e4ab-4ec7-b563-b89ed4ace4c3)
![icon](https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/d24096d7-0e81-4b79-99d2-debfbf6d7c22)

**Comment by MarkisDev** [comment]
This optimization was proposed by @superiorsd10 as well. The reason we didn't go ahead with it was that we were planning to change the way this information would be displayed (which would make it different for each feature). 

I think we'll redo the code when it comes to it. Please put up a PR :)
