### ISSUE TITLE
Quotes Feature in Alarm Setting

### ISSUE THREAD

**Issue by andoriyaprashant** [CCExtractor/ultimate_alarm_clock#136]
### Description

Proposing a transformative addition to the alarm setting in the app by suggesting the integration of a new feature: Randomized Quotes feature into Alarm Setting. As part of this proposal, users would have the option to enhance their wake-up routine with positivity as the system dynamically presents a motivational quote or tip just during the alarm configuration process. With a collection of 20 - 30 inspiring messages, this proposed feature adds an element of surprise and encouragement to each alarm setting. Users can choose to opt into this experience, turning the task of setting alarms into a delightful and personalized moment. Seamlessly integrated into the alarm-setting workflow Under the label option, I want to add the quotes feature, this proposal aims to bring a daily dose of motivation to users as they prepare for a new day. 

### Screenshots

![Screenshot_20231113_203411 1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/121665385/da44f4d5-2731-497a-a429-86b6ebeb5cac)

**Comment by andoriyaprashant** [comment]
Hey @MarkisDev I'd like to work on this issue. It's a valuable addition to our project. 
Please consider assigning it to me if you find it suitable.
Thank you

**Comment by MarkisDev** [comment]
It's definitely a nice addition. Could you elaborate more on how you'll fetch these quotes? Are you planning to use an API or store these quotes locally?

**Comment by andoriyaprashant** [comment]
APIs can also be used, but storing quotes locally 
Reduced Dependency: No reliance on external APIs, reducing potential points of failure and If you want I can also make use of APIs @MarkisDev

**Comment by MarkisDev** [comment]
Using API is definitely better because we'll probably get access to a huge repository of quotes - but it might not work when there's no internet.

I think local storage of quotes is better, just make sure it's displayed at random. We'll just maintain a bunch of quotes because just 20-30 will get repetitive.

**Comment by andoriyaprashant** [comment]
Okay, I will work on this feature through the API @MarkisDev 👍🏻

**Comment by MarkisDev** [comment]
> Okay, I will work on this feature through the API @MarkisDev 👍🏻

I'm sorry if I confused you - please go with storing the quotes locally, picking one at random maybe. Just make sure there's more than 30 quotes so it doesn't get repetitive.

**Comment by andoriyaprashant** [comment]
No no its okay I will work on this through APIs no problem 
this will also give me the opportunity to work on APIs 
If any doubts arise, I will discuss them with you

**Comment by its-me-abhishek** [comment]
We can implement this using a JSON that has 300+ quotes (and may add more later on - they're pretty easy to generate). 
I have made one of such JSONs earlier and can provide it if required.
Using JSON will help us to implement this feature locally.

**Comment by MarkisDev** [comment]
> No no its okay I will work on this through APIs no problem this will also give me the opportunity to work on APIs If any doubts arise, I will discuss them with you

API won't really be sustainable unless there is Internet connectivity and like you mentioned it's a potential point of failure. I prefer the JSON approach suggested by @its-me-abhishek.

**Comment by andoriyaprashant** [comment]
> > No no its okay I will work on this through APIs no problem this will also give me the opportunity to work on APIs If any doubts arise, I will discuss them with you
> 
> API won't really be sustainable unless there is Internet connectivity and like you mentioned it's a potential point of failure. I prefer the JSON approach suggested by @its-me-abhishek.

Okay, I will try using the JSON approach and submit the pull request as soon as possible

**Comment by MarkisDev** [comment]
I'll assign this to you since it's related to #253. @superiorsd10
