### ISSUE TITLE
org.gradle.java.home Issue while setting up the project locally on Mac

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#14]
Issue 
While setting up the project in my Mac it saying the following error
<img width="642" alt="Screenshot 2023-06-24 at 4 33 01 PM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/8c0ce7b4-5d55-4859-8b4f-c458983334e9">

Cause
The jdk path is explicitly specified in org.gradle.java.home file in the 4th line as mention in the below pic which may be different for each local machine
![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/fadad5b9-0ef2-4829-8dc2-9ea8158ab873)

**Comment by MarkisDev** [comment]
Ah yes, sorry about that. Thanks for raising this!
