### ISSUE TITLE
In Light Mode the Weather Condition's Info's (UNDERSTOOD Button text) had a different color compare to all other Info (UNDERSTOOD Button) 

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#148]
### Description

When Light Mode is enabled, the button for the Weather Conditions Info (Understood button text) had kLightSecondaryTextColor,
which should be kLightPrimaryTextColor.

How to Produce the issue-
Cick on Add or Update alarm button.
Navigate to Weather Condition Tile.
Click on Info button, Now You can see the Understood button text color. 

Could you please assign this issue to me?

### Screenshots

Issue-
![issue](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/47fff665-834a-4e14-a411-ab58a22e896f)

Some example how it should be-
![example0](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/008cda11-1360-4e72-96c7-90cdb2093d86)
![example1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/ec9d9e2d-afcb-4c60-8899-c97b39589d1d)

After fixes-
![fixed](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/763ce596-24a4-45ff-a939-e4c1ffead0a9)

**Comment by MarkisDev** [comment]
I've assigned this to you.

**Comment by its-me-abhishek** [comment]
@sameermansoori1 I think that #135 has already fixed this issue.
![1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/e13d4e22-7f00-4ec6-aa56-4d9105f6f390)
![2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/79160981-7e0b-4b57-91f6-f21421842d52)

**Comment by MarkisDev** [comment]
Oh right, with the new function, this should be fixed. Closing it, thanks for bringing it to my notice @its-me-abhishek!
