### ISSUE TITLE
Feature: Adding Controller to Repeat tile Font Weight.

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#149]
### Description

Currently, the Repeat tile has a fontweight that does not go with it when the repeat tile is set to Never.
I think adding a controller to it provides a better User Interface.
 This means when it is set to never its font weight should be normal like all,
After selecting any particular day or days make the Repeat tile show like it is active now.

Could you please assign this to me?

### Screenshots

Present-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/f9a7cb76-b3d7-48e5-9e0c-fb5f9403ef87

After adding Controller-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/6c20e14b-33b5-470e-8816-91ce66ac462a

**Comment by MarkisDev** [comment]
I've assigned this to you.
