### ISSUE TITLE
Deprecation: WillPopScope has been deprecated

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#151]
### Description

`WillPopScope` widget is deprecated in the newly released version of Flutter. 

So we should replace it with the `PopScope` widget. 

_I would like to work on this issue, so please consider assigning it to me._

**Comment by MarkisDev** [comment]
Yeah that would be a good idea to do, assigning to you!

**Comment by the-dapp-coder** [comment]
@MarkisDev  Is this issue still open? if so, I'd like to work on this.
Thank you.
