### ISSUE TITLE
Issue: Font Weight Inconsistency in Repeat and Weather Tiles

### ISSUE THREAD

**Issue by Adarshkumar167** [CCExtractor/ultimate_alarm_clock#152]
### Description
There is a noticeable inconsistency in font weight within the Repeat and Weather tiles. The font weight appears to be set unnecessarily, impacting the visual presentation of these tiles. This inconsistency affects the overall user experience.

**Request**
Could you please assign this issue to me?

Before
![WhatsApp Image 2023-11-17 at 13 53 47_22161506](https://github.com/CCExtractor/ultimate_alarm_clock/assets/75246773/550fb9ed-692a-4a29-ab61-193a216e780d)

After
![WhatsApp Image 2023-11-17 at 13 53 47_ccb19c2d](https://github.com/CCExtractor/ultimate_alarm_clock/assets/75246773/61404e5d-f736-4d66-9397-e1f2f7adce37)

**Comment by MarkisDev** [comment]
Sure, please put up a PR!

**Comment by MarkisDev** [comment]
This looks similar to #149, I think you should fix the weather font-weight and leave the repeat to @sameermansoori1 :)
