### ISSUE TITLE
UI Fix : Color inconsistency

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#154]
### Description

![Screenshot 2023-11-17 at 7 30 12 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/9b11b547-297b-45d1-bf6b-d4791eb07610)
![Screenshot 2023-11-17 at 7 36 07 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/9477106b-fce6-4ca6-aebc-f96061464f81)

There color scheme of the switch is not well when we change the theme

**Comment by MarkisDev** [comment]
I am using the latest build of the code but I'm unable to replicate this - the switches seem fine to me on light and dark mode. Any particular way to replicate this?

**Comment by MarkisDev** [comment]
Closing this issue, fixed with #189
