### ISSUE TITLE
Bug: TimePickerSpinner gets rebuilt on scrolling the view

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#158]
### Description

When we change the time on the `TimePickerSpinner` widget (for example to 03:45 AM), and then scroll to the end of the view, and then scroll up,  the `TimePickerSpinner` widget gets rebuilt (i.e. the time changes back to the original, and not 03:45 AM).

 _I would like to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/0aca72d5-4673-409c-8a7d-b475e2c326b9

**Comment by MarkisDev** [comment]
Oh, I hadn't noticed this at all. Thanks for catching it, I'll assign this to you. Let me know if you get stuck somewhere!

**Comment by superiorsd10** [comment]
> Oh, I hadn't noticed this at all. Thanks for catching it, I'll assign this to you. Let me know if you get stuck somewhere!

Yes, thank you for assigning it to me, and I'll let you know if I get stuck anywhere. 

Thank you,

**Comment by superiorsd10** [comment]
@MarkisDev I think this issue can be closed now as it's resolved by this [PR](https://github.com/CCExtractor/ultimate_alarm_clock/pull/153).
