### ISSUE TITLE
Docs: Addition of Code of Conduct File

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#159]
I propose the addition of a Code of Conduct file to enhance the inclusivity and positive community engagement within our open-source project. 

We can add a dedicated `CODE_OF_CONDUCT.md` file to root of the project, and can use established open source templates such as the [Contributor Covenant](https://www.contributor-covenant.org/) as the starting point. 

_I would like to work on this issue, so please consider assigning it to me._

**Comment by MarkisDev** [comment]
I've assigned this to you!

**Comment by superiorsd10** [comment]
> I'm not sure I like these things in a purely technical community.
> 
> Eventually the conversations become political and not technical.

Will it be good if we make our code of conduct that is purely technical?

**Comment by MarkisDev** [comment]
Carlos said that the project seems to be active with collaborators contributing for now. I think we can revisit this in the future if needed.
