### ISSUE TITLE
Docs: Addition of Contributing File

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#160]
I propose the addition of a `CONTRIBUTING.md` file to provide clear guidelines for contributors, streamline the onboarding process, and foster a collaborative environment within our open-source project. 

We can add a dedicated `CONTRIBUTING.md` file to the root of our project. This file should cover some important aspects such as:-

- How to set up the development environment? 
- Guidelines for submitting bug reports and feature requests (in general creating an issue).
- Code contribution guidelines (branching, pull requests, etc).
- Coding standards and best practices.

_I would like to work on this issue, so please consider assigning it to me._

**Comment by MarkisDev** [comment]
Please go for it :)
