### ISSUE TITLE
Docs: Improving the repo Readme  

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/ultimate_alarm_clock#161]
### Description

# Problem Description: 
The current README lacks some essential features that can enhance user understanding and project visibility

# Proposed Changes/Solution
- Currently, the readme lacks some features such as: 
   - Badges to showcase project status, license, version, and other relevant information. Badges provide quick insights into the project's health and status.   
   - Include screenshots or GIFs showcasing different parts of the application. Visuals provide users with a quick overview of the app's interface and features.
   - Any other information about the application including the tests, guidelines, security, permissions explanation, resource usage, etc.

Please consider assigning this issue to me if you find it to be acceptable.

**Comment by MarkisDev** [comment]
I've assigned this to you!

**Comment by its-me-abhishek** [comment]
Hey! thanks for assigning this issue to me. I've come across a few issues. Please specify the licenses of the app.
