### ISSUE TITLE
Top Navigation Bar overflowing when we long press on the alarm tiles to select them.

### ISSUE THREAD

**Issue by SATVIKSH** [CCExtractor/ultimate_alarm_clock#172]
### Description

When we select the alarm tiles to delete them, the top navigation bar is overflowing out of the screen. I would like to work on this  issue if it is assigned to me.

### Screenshots

![issue](https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/b16d69c5-f1ed-43f1-9948-0ca4ee9bf40c)

https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/1ca4c661-4c9e-40cc-916d-3571cbab4afe

![issue](https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/9059e534-330f-47e7-855c-14e514fe93a9)

**Comment by sameermansoori1** [comment]
Hey @SATVIKSH, Brother, I suggest updating your branch to the latest commit and then re-upload the screen recording of the issue.

**Comment by SATVIKSH** [comment]
Sure @sameermansoori1. Here is the screen recording with the updated branch.


https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/86f24f0d-061f-4bb9-8cce-11bc13cbf295

**Comment by pranavkonidena** [comment]
Hey, could you please assign this issue to me? Am already working on the fix, shouldn't take long

**Comment by the-dapp-coder** [comment]
Hello @MarkisDev, I'd like to take up & work on this issue, can you please assign it to me if no one if working on it or so...?
Thank you for your time.

**Comment by SATVIKSH** [comment]
> Hello @MarkisDev, I'd like to take up & work on this issue, can you please assign it to me if no one if working on it or so...?
> Thank you for your time.

Hello @the-dapp-coder , I want to inform that currently I am working on the issue.

**Comment by the-dapp-coder** [comment]
Not an issue @SATVIKSH, keep on it, I'll pick another one.
Sorry for the inconveniences, all the best!

**Comment by SATVIKSH** [comment]
No problem @the-dapp-coder , all the best !

**Comment by MarkisDev** [comment]
I've assigned this to you @SATVIKSH. Please put up a PR!
