### ISSUE TITLE
Bug: Textfield of 'Open Weather Map API' not checking empty string

### ISSUE THREAD

**Issue by prince02765** [CCExtractor/ultimate_alarm_clock#175]
### Description

In settings, Open Weather Map API TextField has no 'isEmpty' string-checking mechanism before identifying whether it's correct or wrong.

Desired output:
First It should be checked whether TextField is empty or not.

**Could you please assign this issue to me?**

### Screenshots

How to produce this issue:

https://github.com/CCExtractor/ultimate_alarm_clock/assets/69643676/50240708-3470-4338-9a7f-66efe2a70f2c

<br>
Device Name: Samsung S20 Ultra
<br>
Android Version: Android 13

**Comment by the-dapp-coder** [comment]
Hey @prince02765, I'd like to take up the issue if it's still open. Please let me know,
Thank you.

**Comment by MarkisDev** [comment]
I'm sorry, I couldn't understand this issue. Are you proposing to check if it's empty before making the request?

**Comment by MarkisDev** [comment]
Alright, I'll assign this to you.
