### ISSUE TITLE
Bug: Handling barier dissimisal conditionals for all the dialogues in add_or_update_alarm_view page

### ISSUE THREAD

**Issue by the-dapp-coder** [CCExtractor/ultimate_alarm_clock#179]
### Description

Whenever we create/update an alarm, there are certain dialogues we open to update values, like repeat, snooze duration, screen activity, shake to dismiss, & maths. When we select certain values in these dialogues & click any place outside the dialogue (area outside the dialogue) instead of clicking on save or cancel, the dialogue saves the values automatically.
The above behavior is not conventional, generally, the dialogue should save the values only after selecting the "save" button &  cancellation of dialogue means restoring the values to their previous state. 
I can propose two solutions I can think of which are as follows,
1. We can reset the values to default on barrier dismissal
    e.g.: if the "screen activity(timeout duration)" default value is 0 then we will reset it to 0 after barrier dismissal, no matter the 
   current selected value as it's not saved yet.
2. We can set the value to its previous state after cancellation.
   e.g.: if the "screen activity(timeout duration)" preselected value is 5 then we will set it to 5 after barrier dismissal, no matter the 
   currently selected value as it's not saved yet.

I've started working on the first approach, but please let me know if I should work on second one or some other appproach, I'll update the conditionals accordingly.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/51785772/105e9efa-b45c-40e3-8251-29770a51242d

**Comment by MarkisDev** [comment]
This isn't really a bug - I intended it to be like this. However, I see your point. With the Done button it makes more sense to save the values when it's clicked.

If someone has selected the value of Screen Duration to 5 and presses done, it should be set at 5. The next time they open Screen Duration and sets it to 7 but this time they press outside the dialog. The value of Screen should be set as 5 as they had chosen it as 5 before.

Hopefully that makes sense, I'll assign this to you!

**Comment by the-dapp-coder** [comment]
> This isn't really a bug - I intended it to be like this. However, I see your point. With the Done button, it makes more sense to save the values when it's clicked.
> 
> If someone has selected the value of Screen Duration to 5 and presses done, it should be set at 5. The next time they open Screen Duration and set it to 7 but this time they press outside the dialog. The value of the Screen should be set as 5 as they had chosen it as 5 before.
> 
> Hopefully that makes sense, I'll assign this to you!

Surely, that's the second approach I proposed in the issue itself, I've already written & tested code for that locally, I'll just test it again & push it in the same pull request associated with this issue.
Thank you for the quick response @MarkisDev
