### ISSUE TITLE
UI Fix: Material3 theme is on by default

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#184]
### Description

In the newer versions of Flutter, the `useMaterial3` property has been assigned to `true` by default. So it's impacting the overall theme of our application. 

We'll have to set it to `false` in our `ThemeData` in the `constants.dart` file. 

_I would like to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/8b7a760f-5e01-4213-80ed-623cd69d2737

**Comment by MarkisDev** [comment]
I've assigned this to you

**Comment by MarkisDev** [comment]
That's not an issue, we'll go ahead with disabling it for now. The new switches don't look very good imo.
