### ISSUE TITLE
Feature: Adding 24 hour format option for entering time.

### ISSUE THREAD

**Issue by SATVIKSH** [CCExtractor/ultimate_alarm_clock#187]
### Description

An option for entering time in 24 hour format can be added to the project. I would like to work on this issue if it is assigned to me.

**Comment by MarkisDev** [comment]
Sounds great, maybe make an option in settings to enable 24H format throughout the app!

**Comment by cfsmp3** [comment]
I literally just asked for this today before seeing this :-)
Absolutely essential before release, am/pm is not a thing in many countries.
