### ISSUE TITLE
Bug: Custom ringtone can be enabled with no ringtone chosen

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#188]
### Description

Currently, if I enable the Custom Ringtone feature, and don't choose any custom ringtone audio from my device, I can still click on the `Done` button. But no ringtone will be played when an alarm rings. 

If a user has enabled the Custom Ringtone feature, then we'll have to make sure that they can't close the dialog or click on the `Done` button without choosing the custom ringtone audio or they can also disable the feature.

_I would like to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/4fe8bbfe-b7c1-463e-8563-caa7165faf80

**Comment by MarkisDev** [comment]
I've assigned this to you.
