### ISSUE TITLE
Feature: Show a snackbar when user uploads a custom ringtone with size >= 16MB

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#191]
### Description

Currently, when the user uploads an audio file of size >= 16MB for the custom ringtone feature, the app breaks. It's because of the [Isar Database's Object Size Limitations](https://isar.dev/limitations.html) which states that "Objects can only be 16MB in size".

So I think we should show a warning snackbar whenever the user tries to upload an audio file with size >= 16MB.

_I would like to work on this issue, so please consider assigning it to me._

**Comment by MarkisDev** [comment]
This wouldn't be necessary with #190 right? In that case I shall go ahead and close this issue.

**Comment by superiorsd10** [comment]
> This wouldn't be necessary with #190 right? In that case I shall go ahead and close this issue.

Yes, as we're changing the whole implementation, we don't need this issue.
