### ISSUE TITLE
Bug: Bug issue template doesn't show "Bug: " title

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#192]
### Description

Currently, when we try to create an issue of type `bug`, the issue template doesn't show the "Bug: " title. However, it does show the "Feature: " title when we create an issue of type `feature`.

So, I think we should add a title to the `bug.yaml` file in the `ISSUE_TEMPLATES` under the `.github` folder.

_I would like to work on this issue, so please consider assigning it to me._

### Screenshots

![SCR-20231209-jit](https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/e6230895-03ba-4923-8f46-e4e1a15b4965)

**Comment by MarkisDev** [comment]
I've assigned this to you
