### ISSUE TITLE
Feature: setting values to previous state on custom ringtone barrier dismissal

### ISSUE THREAD

**Issue by therushdevs** [CCExtractor/ultimate_alarm_clock#195]
### Description

The issue is in reference the  issue #179, 
When the custom ringtone dialogue is dismissed, the values get saved without even saving them which is shown in the video shared below.
Possible Fix:
The fix will be to set the values to the previous state when the barrier is dismissed instead of saving. I'll be creating the PR for it soon.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/51785772/565f223b-1061-4ec0-899e-4c32c765c287

**Comment by superiorsd10** [comment]
Thanks for noticing it :) @the-dapp-coder

**Comment by the-dapp-coder** [comment]
> Thanks for noticing it :) @the-dapp-coder

he he, just resolved the same kinda issue with dialogues, so, just checking other dialogues on the way... :)

**Comment by MarkisDev** [comment]
I've assigned this to you @the-dapp-coder

**Comment by superiorsd10** [comment]
@the-dapp-coder maybe you should wait to work on this issue as this file is going to be deleted in the upcoming PR.

**Comment by the-dapp-coder** [comment]
> @the-dapp-coder maybe you should wait to work on this issue as this file is going to be deleted in the upcoming PR.

sure, please let me know when this happens, I'll keep an eye too.
