### ISSUE TITLE
Feature: Enhance Alarm Dismissal with a Quick Note Feature

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/ultimate_alarm_clock#200]
### Description: 
Currently, the app lacks a feature that may allow users to set custom quick notes when setting an alarm. Users may want to add personalized notes that appear when the alarm goes off, enhancing their morning routine and providing additional context or reminders.

### Proposed solution: 
Implement a feature that enables users to set custom quick notes while setting an alarm. These notes should be displayed on the alarm dismissal screen, providing users with a personalized message when they wake up or simply, the alarm goes off. The implementation involves:

- Provide with an option (a dialog box) to add a quick note on the "add a new alarm" screen.
- If provided with a quick note, it would show up on the screen when the alarm goes off.
- Else, it just goes the vanilla way, i.e. no quick note, if not provided with one.
- Usage of shared preferences or a local database for storing the quick note.

### Example:
- The user sets a new alarm.
- During the alarm setting process, there is an option to add a custom quick note.
- The user enters a note such as "Have a productive day!" or "Remember to bring lunch." or some other note.
- The note is stored locally and associated with that specific alarm.
- When the alarm goes off, the note is displayed on the alarm dismissal screen.

Please consider assigning this to me if you find this to be acceptable

**Comment by superiorsd10** [comment]
Nice idea, man! But don't you think that the `Label` feature also serves the same purpose. Like the user kind of uses the `Label` as the quick note.

**Comment by its-me-abhishek** [comment]
You are right but the `Label` serves as the identifier for alarms, distinguishing their context on the home screen. The proposed enhancement involves displaying the quick note on the post-alarm splash screen, positioned above the snooze and dismissal buttons.

**Comment by MarkisDev** [comment]
Yeah, that makes sense - I'll assign this to you!
