### ISSUE TITLE
Feature:  Add a "Tick" or "Done" button feature in the "add_Or_Update_alarm", which will allow us to confirm it with button in the app as well after enter the time manually.

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#201]
### Description

When we manually enter the time in a text field and want to complete the task, we have two options. Firstly, we can click anywhere on the screen to exit the text field. Secondly, we can click on the "done" button located on the soft keyboard.

To improve the user experience of the app, I suggest adding a dedicated "Tick" or "Done" button on the top of the app bar. This button should only be visible when the user clicks on the timePickerSpinner to enter the time manually. This will make it more convenient for the user to confirm their selection and provide a better overall experience.

Could you please assign this issue to me?

### Screenshots

Present-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/e3c52d2b-d4f8-44ed-b4ff-b787f3ca2b06

After adding the button-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/10b579ae-90d4-42d9-b039-0dadd330d54f

**Comment by MarkisDev** [comment]
That should be fine, but instead of adding it on the app bar - i think you should add it below the input field (the space between input and repeat) 

People would easily miss the button on the app bar.

**Comment by sameermansoori1** [comment]
"Please take a look at this." @MarkisDev 
I think it looks odd between the input field and repeat tile. I think this is much better. 
I tried to add an outlined button(done), but it didn't fit the UI.

"I decided to place it in the same row."
[

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/fff492ea-b344-469f-9ec6-c416cfd2741b

**Comment by MarkisDev** [comment]
That space is good too, but can we make it more obvious to look like a button? It doesn't necessarily have to be just an icon, could be text too. Whatever fits better.

**Comment by sameermansoori1** [comment]
"Please take a look at this." @MarkisDev 


https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/6e0c248f-79f0-40e1-b9c0-8678bed46f5b

**Comment by MarkisDev** [comment]
This looks much better, please put up a PR! :)
