### ISSUE TITLE
Feature: Auto Delete an alarm once it goes off

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/ultimate_alarm_clock#202]
## Description:
I would like to propose a new feature that allows users to choose whether an alarm should be automatically deleted once it goes off. This can be very useful for users who want a set-and-forget approach to alarms without cluttering their app with past alarms.

## Proposed solution: 
- When creating a new alarm on the add alarm screen, the users should have an option (a toggle) to enable or disable automatic deletion of that particular alarm (disabled by default).
- If enabled, the alarm should be removed from the list once it has been dismissed.

Please consider assigning this issue to me if you find it to be acceptable :)

**Comment by MarkisDev** [comment]
I think this would be a great feature but it will have to work in coordination with the custom ringtones feature that has been implemented - I'll merge the PR by @superiorsd10 and then you can begin working on this.

**Comment by its-me-abhishek** [comment]
Sure I'll wait and start working on it once that PR gets merged

**Comment by superiorsd10** [comment]
@its-me-abhishek It's a really good idea, man!
