### ISSUE TITLE
Feature: Snooze window enhancement

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#207]
### Description

I would like to add a button in the snooze window where user can increase current snoozing time to 3x or 2x as per the need

**Comment by saurav0523** [comment]
@BrawlerXull can i work on this??

**Comment by MarkisDev** [comment]
You can find more info on this issue in #204 @saurav0523

**Comment by vkprogrammer-001** [comment]
can I work on the issue?  if the issue is still open.

**Comment by mohnishdeshpande** [comment]
@BrawlerXull The feature has been implemented. Please have a look.
