### ISSUE TITLE
Feature: Adding a screen for open weather api info

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#208]
### Description

I would like to add a screen after clicking the open weather button explaining how to get that key

**Comment by MarkisDev** [comment]
I've assigned this to you.

**Comment by sagarrajgit** [comment]
are you still working on it, if you aren't then I would like to work on it

**Comment by MarkisDev** [comment]
Feel free to put up a PR @sagarrajgit

**Comment by sagarrajgit** [comment]
This is what I made for English
![1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/60acd384-beff-46ee-9b40-4ec5223f1d7a)

what should do for other languages, just convert using google or something else.
