### ISSUE TITLE
Enhancement: Adding gradient to the alarm sound

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#212]
### Description

I would like to add gradient to the alarm sound

**Comment by MarkisDev** [comment]
Yeah, please go ahead with it.

**Comment by its-me-abhishek** [comment]
I would like working on this issue if it is stale. @BrawlerXull @MarkisDev

**Comment by MarkisDev** [comment]
Feel free to put up a PR @its-me-abhishek
