### ISSUE TITLE
Enhancement: Changing the text in about section

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#214]
### Description

I would like to the add the following text in the about section of the applicaiton
`This project was originally developed as part of Google Summer of code under the CCExtractor organization. It's free, the source code is available, and we encourage programmers to contribute.
In about, also add a link to Google Summer of Code website.`

**Comment by MarkisDev** [comment]
I've assigned this to you, please don't forget to change the version number here as well.

**Comment by MarkisDev** [comment]
Fixed with #215
