### ISSUE TITLE
Feature: Explanation for Google sign-in and fix for auto-login

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/ultimate_alarm_clock#219]
### Description

Reference: #204

## Proposed solution:
- Instead of redirecting the user directly to the screen where they choose a google account for sign in, we could first redirect 
them to a dialog box, or a page ( as preferred )
- That page/dialog would have the required FAQs and explanations as to why they must sign in. For example:
  - Easy Access: Sign in quickly without creating a new username and password.
  - Sync Across Devices: Access your alarms and settings on multiple devices seamlessly.

The auto-login issue, lacking user prompting, is linked to the authentication flow's implementation.
- The automatic selection of the previously logged-in account on the splash screen post the initial sign-in is a potential cause.
- Similar behavior is observed in features like auto-login in Google Play Games, etc.
- A solution involves either replacing the sign-in bar with a logout button after a successful login, or providing a logout button at the end of page, providing users with a clear option to sign out and choose a different account. Reviewed the sign in documentation for this it states that 'To provide a seamless experience, Automatic Sign-in removes the manual steps to sign in when you return to an app or service. A dialog box shows the process of the sign-in as it occurs.'
- Can be fixed by prompting the user to force choose an account in firebase or implementing a log out button so the user would necessarily have to sign in once again and choose his preferred account promptly.

**Comment by MarkisDev** [comment]
A dialog should be fine - apart from syncing alarms it's absolutely essential to login to be able to use Shared Alarms. I'll assign this to you, feel free to ask me anything if you get stuck.

**Comment by its-me-abhishek** [comment]
hey! please review the text for the dialog box and suggest any changes that must be made it.

## Why Sign In with Google?

### Shared Alarms:
Collaborate with friends, family members, or colleagues to ensure that they wake up on time using shared alarms.

### Syncing Across Devices:
Access your alarms across multiple devices where the alarms are updated in real-time.

**Comment by cfsmp3** [comment]
I'd say

Why Do I have to Sign In with Google?

Signing in is optional. It's only required for the functionality that uses
cloud services to work such as
Shared Alarms:

Collaborate with friends, family members, or colleagues to ensure that they
wake up on time using shared alarms.
Syncing Across Devices:

Access your alarms across multiple devices where the alarms are updated in
real-time.
Your privacy

We don't access,  use or sell any information, which you can verify by
inspecting the source code.

All access is limited exclusively to provide the functionality described
above.

**Comment by its-me-abhishek** [comment]
thanks! will try implementing this asap

**Comment by its-me-abhishek** [comment]
<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/77346a11-4f8b-4c34-8537-96c80d4f717b" height="550">
<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/d16a950d-746c-43c2-a163-342d332871b8" height="550">

I have implemented this dialog box so far, the sign in button leads to the choose accounts screen (hidden the accounts here). Please review this.

**Comment by MarkisDev** [comment]
It does look a little awkward with a dialog having so much text, I didn't think we'd have so much text. Alternatively, maybe you could move this to a bottomsheet using GetX? It shouldn't be too much rework and would be much cleaner imo

**Comment by its-me-abhishek** [comment]
Sure, I'll move this to a bottomsheet. Another idea that came across was that instead of redirecting the user to the dialog/sheet and then to the Account selection page, we could just have an `i` icon just like the ones in the `Add alarm` page that shows the explanation if required, and not everytime when the action is triggered.
