### ISSUE TITLE
Bug: Location activity feature not working

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#220]
### Description

While creating the alarm, if I'm using the location-based feature, and choosing a location where the alarm won't ring, it's still ringing. 

I chose the exact location where I'm currently, but still, it does ring. The alarm ringing screen appears, but there isn't any sound, and then the app closes instantly. On opening the app again, it shows the alarm ringing screen. 

_I would like to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/75b39f4e-44dd-47b9-9671-2f26f1a18cf3

**Comment by MarkisDev** [comment]
The alarm doesn't ring, it goes to the "/alarm-ring-ignore" route to minimize the application after performing the necessary operations on the database. 

With the new implementation, we have to remove the /alarm-ring-ignore screen though - maybe you could delete that route and move the logic to update db and minimize after redirecting to home within the splashController itself. That should clear up the confusion. I'll assign this to you!

**Comment by superiorsd10** [comment]
@MarkisDev Should we completely remove the `alarm-ring-ignore` as it's not being used anywhere now?

**Comment by MarkisDev** [comment]
That would be the way to solve this. You'd have to add the necessary logic to update the alarm record within the splash controller itself. If it's blocking the UI too much, then we'd have to think about spawning an isolate to handle this - although I'm not sure if we can run firestore queries in the isolate.
