### ISSUE TITLE
Bug: Splash screen appears when the alarm rings

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#221]
### Description

Currently, when the alarm rings, the application opens up again, a splash screen shows up, and then finally the alarm ringing screen appears. On dismissing the alarm, it navigates to the home screen. 

The ideal behavior should be like it was before when we were using the foreground services, the application shouldn't open up again, and this way the splash screen will not be shown. 

_I would like to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/08e4fec7-8bb2-4517-8139-99176ef7ac73

**Comment by DarkCoder26** [comment]
I am new to Open Source I would like to work on this issue

**Comment by DarkCoder26** [comment]
I am new to Open Source and If this Issue is not closed then I would like to work on it.

**Comment by vkprogrammer-001** [comment]
if nobody is working on the issue. I want to work on it. @MarkisDev can you please assign this to me?

**Comment by MarkisDev** [comment]
@vkprogrammer-001 Sure, but please do keep what I've said earlier here in mind. Let's discuss for a solution before putting up a PR for this :)

**Comment by vkprogrammer-001** [comment]
@MarkisDev ok
