### ISSUE TITLE
Feature: Repetition of alarm - Improved Alarm Setup 

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/ultimate_alarm_clock#222]
## Description: 
Reference: #204 'I'm trying to setup a one-time alarm for Monday, but I can't (there's no way to select the day of the week for a one time alarm). I saw I can select the day of the week under the Repeat field. I think it would be better to call that field "Days of the week" then, and by default select the one in which the alarm would ring (i.e. today or tomorrow, depending on the current time and the alarm time).
-Repeat once is confusing. Does it mean it would ring twice?'

## Proposed solution:
I suggest introducing a 'Repeat' dialog with four clear options:

- Once: For a single occurrence (the next day).
- Daily: Automatically selects the whole week.
- Weekdays: Selects Monday to Friday (excluding the weekend).
- Custom: Provides flexibility for users to select their preferred days (As it is now).

I would like to work on this issue, so please consider assigning it to me.

**Comment by its-me-abhishek** [comment]
Instead of `Repeat once`, we could rename it to `Ring once` as we're setting it to ring on Monday and not on the next Monday aswell. 
Or we may just add a modal functionality similar to the Screen activity, etc. and explain its working there for some intuitive experience

**Comment by MarkisDev** [comment]
Repeat Once essentially makes it so that the alarm will ring once on the days selected under repeat. You can rename it to "Ring once".
If its set to never, it won't repeat on any day, just ring the next day or the same day (depending on alarm time).

**Comment by its-me-abhishek** [comment]
Sure. Also, I'll add an info button for the ring once tile. Will submit a pr after implementing these features.
