### ISSUE TITLE
Refactor: Remove the app's dependency on flutter_ringtone_player

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#223]
### Description

Currently, the app uses `flutter_ringtone_player` for playing the device's default ringtone, and `audioplayers` for playing the custom ringtone from the stored path. 

But it's not feasible to have an audio package for only playing the device's default ringtone. So we should remove our app's dependency on the `flutter_ringtone_player` package.  

I propose a solution in which we can use the `MethodChannel` to invoke the platform-specific code and achieve the functionality of playing the device's default alarm ringtone. 

This way we'll only be using the `audioplayers` package, and we also don't need to bundle a specific ringtone file with the app's assets. 

_I would like to work on this issue, so please consider assigning it to me._

**Comment by MarkisDev** [comment]
Yeah, I definitely want to remove the dependency on flutter_ringtone_player. Using MethodChannels to play the default alarm sounds great, but it could get tricky. Let me know if you get stuck.

I'll assign this to you but you can begin on this once the PR is merged.

**Comment by MarkisDev** [comment]
This should now be possible with #203

**Comment by superiorsd10** [comment]
> This should now be possible with #203

Yes, thanks for merging it in. I'll be working on it as soon as possible.
