### ISSUE TITLE
Refactor: Implement error handling in input time controller

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#227]
### Description

Currently, when we want to set the alarm time through the input field, and if we clear everything in any particular field (hour or minute) or type any invalid character that can't be parsed to an integer, the app throws an exception in the terminal. 

So, we should implement error handling in the methods of `InputTimeController` so that the error/exception can be caught, and we can print them in the terminal using `debugPrint`. 

_I would like to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/9b80fca4-28d8-4ceb-938d-78786042db0d

**Comment by MarkisDev** [comment]
Yup, I've assigned this to you.
