### ISSUE TITLE
Bug: Background music don't pause when alarm rings

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#228]
### Description

Currently, if there is some background music playing on the device (e.g. songs), and the alarm rings at that time, the song doesn't pause, and both the song and the alarm ringtone are played simultaneously. 

This results in a very bad user experience. So ideally in this kind of situation, the song should be paused, the alarm ringtone should continue playing, and once it stops, the song should again be resumed. 

I'll be using the [audio_session](https://pub.dev/packages/audio_session) package to implement this functionality. 

_I would like to work on this issue, so please consider assigning it to me._

### Screenshots

_Please turn the volume on :)_

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/163efc9e-e702-42ad-9439-544db22fd137

**Comment by MarkisDev** [comment]
I've assigned this to you.

**Comment by superiorsd10** [comment]
Hey @MarkisDev 👋
I've resolved this issue, once #246 is merged, I'll be making a PR (to avoid merge conflicts).

**Comment by MarkisDev** [comment]
@superiorsd10 #246 has been merged, feel free to put up a PR :)
