### ISSUE TITLE
Feature: Show snack bar when the user sets an alarm

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#229]
### Description

Currently, if the user sets/updates an alarm, the app doesn't show any confirmation about the event. 

I think we should show a snack bar about this alarm-creating/updating event to improve the user experience. The message of the snack bar can be `Rings in 12 hours` (for example). 

_I would like to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/5d75dbbf-b7fe-4850-8993-8d7840c47513

**Comment by MarkisDev** [comment]
I feel like a snackbar would be too much, maybe a toast message?

**Comment by superiorsd10** [comment]
> I feel like a snackbar would be too much, maybe a toast message?
> 
> I've assigned this to you.

Yes, a toast message will be good.
