### ISSUE TITLE
Enhancement: Delay in showing splash screen 

### ISSUE THREAD

**Issue by AnirudhTripathi** [CCExtractor/ultimate_alarm_clock#230]
### Description

SplashScreen shows after a delay of white screen (light mode) or black screen (dark mode). This is due to unoptimised pubspec.yaml for splash screen.

I would like to work on this issue, so please consider assigning it to me

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/89296975/1522fb2c-1e94-4773-9656-916e41a1b702

**Comment by MarkisDev** [comment]
This would be good considering splash controller is increasingly becoming more important for the application. I've assigned this to you.
