### ISSUE TITLE
Refactor: Update the dart and flutter sdk versions in pubspec file

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#231]
### Description

Currently, some of the contributors are facing an issue regarding the `PopScope` widget not working in their environment, and they are getting an error. It's because they are not using the latest version of Flutter. 

Therefore, I suggest that we upgrade the Dart and Flutter SDK versions in the `pubspec.yaml` file to the minimum compatible versions. That way they'll get to know if their SDK version lies in the compatible range, and if not then they can upgrade it. 

_I would like to work on this issue, so please consider assigning it to me._

**Comment by MarkisDev** [comment]
I was thinking about this looking at the message on Slack earlier today. I've assigned this to you :)
