### ISSUE TITLE
Bug:  On alarm ring it does not show label

### ISSUE THREAD

**Issue by AnirudhTripathi** [CCExtractor/ultimate_alarm_clock#233]
### Description

After setting up the label for alarm. When alarm rings it does not shows the label of alarm.

_I would like to work on this issue, so please consider assigning it to me_

### Screenshots

![WhatsApp Image 2023-12-15 at 11 24 53 AM (1)](https://github.com/CCExtractor/ultimate_alarm_clock/assets/89296975/25e8c92f-4df7-4e27-9d11-3e33c08901d4)
![WhatsApp Image 2023-12-15 at 11 24 53 AM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/89296975/5793d986-06c8-49f4-bc2d-b7c524c9969b)
![WhatsApp Image 2023-12-15 at 11 24 53 AM (2)](https://github.com/CCExtractor/ultimate_alarm_clock/assets/89296975/da6e29b1-c44b-4505-9d7f-07f23137ba2a)

**Comment by MarkisDev** [comment]
Labels weren't intended to be shown on the ring screen. There's another issue at #200 which proposes adding a quick note which makes more sense to me. Closing this for now, will reopen if this seems necessary.
