### ISSUE TITLE
Feature: Display Number of Math Questions to solve on math challenge screen

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#234]
### Description

I am thinking of that the number of match question user have to solve or left to solve in order to stop the alarm will be displayed on to the math challenge screen for better user experience
small change I think It would be helpful for user.
@MarkisDev please assign this to me.
Thanks.

**Comment by MarkisDev** [comment]
I've assigned this to you, please make sure it fits well with the UI.
