### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by andoriyaprashant** [CCExtractor/ultimate_alarm_clock#24]
# Description:
Currently, this repository does not have an issue template, which can make it challenging for users to provide all the necessary information when reporting issues or requesting new features. By adding an issue template, we can improve the quality of incoming issues and make it easier for contributors to understand and address them effectively. Additionally, the implementation of an issue template will help raise the community standards on GitHub by promoting consistent and comprehensive issue reporting.

![Screenshot 2023-07-13 170741](https://github.com/CCExtractor/ultimate_alarm_clock/assets/121665385/4096a8d0-8033-45dc-8dba-ae222cbfb98a)

**Implementation:**
- .github/issue_template.md

**Comment by andoriyaprashant** [comment]
Sir @MarkisDev I kindly request to be assigned the task of implementing the "Add issue template" feature in our repository. 
Thank you.

**Comment by MarkisDev** [comment]
Sure thing, feel free :)
I was gonna get the docs and templates done this month, will be helpful!

**Comment by andoriyaprashant** [comment]
Hey @MarkisDev, I have added the issue template. If you want, I can also add a pull request template. I can open a new issue and add the pull request template to it.
