### ISSUE TITLE
Feature: Enable users to create profiles with different alarm settings for various scenarios (e.g., workdays, weekends, vacations)

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#242]
### Description

Enable users to create profiles with different alarm settings for various scenarios (e.g., workdays, weekends, vacations)
Add custom multiple alarm sechdules
Ex = working days sechdule - alarm as 6 am with math challenge and on week ends alarm at 10 am with no challenge on vacation alarm at 7 am 
in this way user able to set alarm accordingly without setting alarm for on each day

Could you please assign this issue to me?

**Comment by MarkisDev** [comment]
Alarm profiles does sound useful, where do you think we can create and set these profiles?

**Comment by Deepanshuigtm** [comment]
I am not sure but we can create a section in settings and on clicking that we can redirect to a new screen where user can configure multiple profiles accordingly like holidays , working, etc  and sechdule alarms

**Comment by Deepanshuigtm** [comment]
@MarkisDev is this good to Introduce 'Alarm Profiles' in settings for managing, configuring, and creating new alarm profiles . Can I start working on it ?
