### ISSUE TITLE
Bug: Prevent Addition of Duplicate Alarms for Same Time

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#244]
### Issue Description:
When users attempt to set multiple alarms for the same time (e.g., 6:00 AM) within the app, the observed behavior is that only the latest alarm among them triggers, while the other alarms are scheduled for the next day

#### Proposed Solution:
if attempting to set multiple alarms for the same time, the app should display an alert message indicating that an alarm for that specific time is already set, preventing the addition of duplicate alarms at that time

Could you please assign this issue to me?

### Screenshots

![WhatsApp Image 2023-12-17 at 2 06 08 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/8b8bcfb0-28ee-4f86-88de-fe9b1f074f32)
![WhatsApp Image 2023-12-17 at 2 06 08 PM-2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/5ecf79c7-0444-45e7-9943-bcf53e48b122)

**Comment by MarkisDev** [comment]
Yeah, this has to be fixed. It could get a little tricky since shared alarms allow for offsets. I'll assign this to you.
