### ISSUE TITLE
Bug: Google sign-in failed in debug mode

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#247]
### Description

Currently, contributors encounter issues related to the addition of the SHA key for the Firebase project of this app, and it results in Google sign-in failing. (Though it works in the release mode.)

To streamline this process and prevent conflicts, I propose creating separate Firebase projects for development and production environments. 

### Steps To Be Followed

- Create a dedicated Firebase project for development purposes. 
- Ensure that contributors add their SHA keys to the development Firebase project.
- Maintain a separate Firebase project exclusively for the production environment. 
- Do all the necessary changes in the codebase (related to the dev and prod environment).

_I would like to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/bdbbb897-1bab-4dcb-92e4-d4af3b8e2f55

**Comment by superiorsd10** [comment]
> I agree with this, however, the app is still in development - l can add some contributors but not all to the firebase. I think it would just be easier for everyone to set up the app on their Firebase account instead - they only require it if they're working with authentication anyway. To make this easier, we can explore flutterfire_cli and make the app work with that.

Yes, that's a great idea.

**Comment by Detective-Khalifah** [comment]
> I agree with this, however, the app is still in development - l can add some contributors but not all to the firebase. I think it would just be easier for everyone to set up the app on their Firebase account instead - they only require it if they're working with authentication anyway. To make this easier, we can explore flutterfire_cli and make the app work with that.

Adding to documentation a guide on the Firebase packages to enable and configure will be helpful.

**Comment by MarkisDev** [comment]
> > I agree with this, however, the app is still in development - l can add some contributors but not all to the firebase. I think it would just be easier for everyone to set up the app on their Firebase account instead - they only require it if they're working with authentication anyway. To make this easier, we can explore flutterfire_cli and make the app work with that.
> 
> Adding to documentation a guide on the Firebase packages to enable and configure will be helpful.

Sure, feel free to put up a PR. It would make more sense to use flutter_fire to make the process easier however.
