### ISSUE TITLE
Bug: Missing ripple effect in settings

### ISSUE THREAD

**Issue by prince02765** [CCExtractor/ultimate_alarm_clock#251]
### Description

- In setting screen, there is a hover effect instead of ripple effect. So, I want to fix this.
- At last, "About" section has no hover effect or ripple effect.

Please assign this issue to me.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/69643676/0afd6b00-551f-48ed-9a80-34da1d0d8550

**Comment by MarkisDev** [comment]
I feel like I like no ripple effect more. How about we remove it from the other tiles as well? I'll assign this to you.

**Comment by prince02765** [comment]
So, you want to remove the ripple effect from the first 3 tiles?

**Comment by MarkisDev** [comment]
Yup, that seems cleaner.

**Comment by Ashfaque9967** [comment]
it's my first time making a PR and i am keep on messing up! Sorry
