### ISSUE TITLE
Feature: Implement pedometer challenge for alarm dismissal

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#252]
### Description

I propose adding a pedometer challenge feature to our application. The goal is to enhance user engagement and promote a healthy morning routine. 

This feature will require users to walk a certain number of steps to turn off the alarm, adding an element of physical activity to the waking-up process. 

### Key Features
- Set a configurable step count that users must achieve to dismiss the alarm.
- Utilize the [pedometer](https://pub.dev/packages/pedometer) package to accurately track the user's steps.
- Define a time window during which users must complete the steps challenge.
- Allow users to enable/disable the pedometer challenge and adjust step count targets in the `AddOrUpdateAlarmView`.

### Potential Benefits
- Encourages physical activity as part of the morning routine.
- Promotes a healthier lifestyle and positive morning habits.
- Adds a unique and engaging aspect to the alarm clock experience.

_I would like to work on this issue, so please consider assigning it to me._

**Comment by MarkisDev** [comment]
This will be quite an interesting challenge. I've assigned this to you!
