### ISSUE TITLE
Bug: The snooze and dismiss buttons are overlapping each other in the alarm preview.

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#256]
### Description

When we click "preview alarm," the snooze button shows beneath the dismiss button.
 I think we should add some padding to it.

Could you please assign this issue to me?

### Screenshots

Issue-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/8f4c7c69-44c1-425e-a178-67c487ed933a

After fixes-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/31ffcf27-f4e2-40fd-98d4-37cb2d336137

**Comment by MarkisDev** [comment]
I've assigned this to you.

**Comment by MarkisDev** [comment]
Could you please put up this PR again?

**Comment by sameermansoori1** [comment]
> [Dec 27, 2023](#event-11342878487)

"Okay, could you please check now?"
