### ISSUE TITLE
Bug: Unable to Delete Ringtone

### ISSUE THREAD

**Issue by tushar11kh** [CCExtractor/ultimate_alarm_clock#262]
### Description

After saving a Ringtone , it does not get deleted even if we add and select some other ringtone. 
Could you please assign this issue to me?

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/144731286/faf5af78-8653-4715-8bc7-1570314c978f

**Comment by superiorsd10** [comment]
Hello @tushar11kh 👋
Can you please add the steps for replicating this issue?

**Comment by superiorsd10** [comment]
Thanks for noticing it @tushar11kh :)

I got the reason why this is happening. We're only decrementing the `currentCounterOfUsage` of any custom ringtone when the ringtone is deleted. But I missed a case that's been demonstrated in the video, it'll have to be decremented when the ringtone is changed in that dialog. The selected one needs to be incremented, and the previously selected one needs to be decremented.

**Comment by tushar11kh** [comment]
Hey @superiorsd10, thank you for looking into the issue. Actually I am a beginner, so thought of taking this issue up and learn more during the process.

**Comment by superiorsd10** [comment]
No worries, man :) Thanks for opening this issue. If you get stuck while working on it, you can ask. You can start working on it once @MarkisDev assigns it to you.

**Comment by MarkisDev** [comment]
Alright, I'll assign this to you @tushar11kh. Don't hesitate to ask anything if you're stuck :)

**Comment by tushar11kh** [comment]
I am sorry about these merge and revert changes, I am new to Git and github too :) . I have submitted my final  [PR](https://github.com/CCExtractor/ultimate_alarm_clock/pull/274) , please do review.
