### ISSUE TITLE
Bug: Alarm not turning off even after completing Maths Challenge

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#263]
### Description

this issue is already raised issue#170. 

I would like to work in this issue

I have set up the maths challenge on easy mode for two questions , But even after solving the two questions the alarm doesn't turn off. After completion of the time period, the alarm restarts and the maths challenge has to be done again. This feature is not working properly.

**Comment by MarkisDev** [comment]
If it's a duplicate of #170, then let's continue the conversation there. Closing this for now.
