### ISSUE TITLE
Bug: Theme Mismatch

### ISSUE THREAD

**Issue by Ashfaque9967** [CCExtractor/ultimate_alarm_clock#265]
### Description

# Description

My system is on dark mode but splash screen is on Light Mode

### Steps to encounter this error

1. Put your phone on dark mode
2. Launch the app

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/110349538/4284c916-a035-4702-96a9-26fa7508d954

**Comment by MarkisDev** [comment]
I'll assign this to you.

**Comment by AdarshRawat1** [comment]
@Ashfaque9967 Are you working on this issue?

**Comment by Ashfaque9967** [comment]
yes i m kinda figuring out how to solve this do you have any suggestion?

**Comment by AdarshRawat1** [comment]
> yes i m kinda figuring out how to solve this do you have any suggestion? @AdarshRawat1

The white background is due to the default behavior of iOS and Android systems. They display a native loading screen before the Flutter's splash screen. 

## Possible solution - 
Modify `launch_background.xml` in the Android directory and set splash screen image as the background of the launch screen.
Add splash screen image to the `Assets.xcassets` folder in the iOS directory.

**Comment by Ashfaque9967** [comment]
@AdarshRawat1 I think its the problem with the theme changing switch in setting if some how we can access the value of switch so maybe the problem can be fixed.
I tried putting my phone in dark mode to test it, then the splash turns black and when system is in light mode the splash screen turn light again even if the theme changing switch is set to dark mode.
do u still think its the problem with the launch_background.xml?

**Comment by AdarshRawat1** [comment]
> @AdarshRawat1 do you still think its the problem with the launch_background.xml?

I am also trying to figure that out, as I faced a similar issue - https://github.com/CCExtractor/ultimate_alarm_clock/issues/301

**Comment by AdarshRawat1** [comment]
I think we'll have to write native codes for this.( platform wise)

**Comment by AdarshRawat1** [comment]
> But running the `flutter_native_splash` package may cause the changes to be overwritten.
 **Suggestion- applicable if we cannot find any other fix**
I suggest setting dark theme as the only splash screen.
It would prevent the user from being flashed and consistency of application will be easier to maintain.

**Comment by MarkisDev** [comment]
Setting the dark theme as the only one is fine if we aren't able to get it to work via native codes.
