### ISSUE TITLE
Feature: Swipe-to-Delete Alarm

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#271]
### Description

The Swipe-to-Delete Alarm Feature enhances the user experience by providing a seamless way to remove alarms. With a simple left swipe gesture, users can swiftly delete alarms they no longer need, streamlining the management of their alarms effortlessly.

Enhanced User Experience: Simplifies the process of managing alarms by introducing a natural and intuitive deletion method.
Efficiency: Saves users time by providing a quick way to remove unwanted alarms without navigating through multiple screens or menus.

**Comment by MarkisDev** [comment]
Yeah, this definitely sounds like it'll make a better user experience. I'll assign this to you.

**Comment by rkverma2022** [comment]
Extending swipe-to-delete #311
At times, users may accidentally swipe and delete content they didn't intend to. Therefore, I suggest incorporating a **pop-up confirmation message** to inquire whether the user genuinely wants to proceed with the deletion.

Hi, I would like to implement it

**Comment by rkverma2022** [comment]
Ok, thanks for your update,

**Comment by MarkisDev** [comment]
@rkverma2022 Feel free to create a new issue to implement this.
