### ISSUE TITLE
Bug: No implementation of systemAlertWindow.isGranted on iOS so the app's functionality on iOS is compromised

### ISSUE THREAD

**Issue by WrathOP** [CCExtractor/ultimate_alarm_clock#278]
### Description

<img width="689" alt="image" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/72385500/c128fe90-67fe-48fd-a9cf-27a392b8bc7b">
<img width="556" alt="image" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/72385500/5aff79f2-8066-4756-8b0a-f49bc712ff02">

I check around on possible fixes that we can do for this and found out if the app is killed you cannot ring alarm and can only send notification for which we can add platform specific code by asking for permission of sending critical alerts from the user

<img width="545" alt="image" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/72385500/d757f9a5-1978-49a1-858a-91ae845c3076">

**Comment by superiorsd10** [comment]
Hello @WrathOP 👋
Thanks for opening this issue. It is related to #224. It's currently being worked on.

**Comment by WrathOP** [comment]
> Hello @WrathOP 👋 Thanks for opening this issue. It is related to #224. It's currently being worked on.

Oh hey sorry I was just looking through and testing the code and found this out , you can work on this issue I was not planning to work on it just because I don't know how I can get it working without some major changes in architecture. I hope you find a elegant solution , would be curious to see what you build and ping me up anytime if you need any help.

**Comment by WrathOP** [comment]
Duplicate issue so I am closing this.....
