### ISSUE TITLE
Feature: Multi-language Support

### ISSUE THREAD

**Issue by sapana-k** [CCExtractor/ultimate_alarm_clock#281]
### Description

Provide support for multiple languages to make the app accessible to a wider audience, thus fostering a global user base.
I'm interested in implementing this feature.

**Comment by WrathOP** [comment]
I would like to implement this feature too

**Comment by MarkisDev** [comment]
I've assigned this to you.

**Comment by MarkisDev** [comment]
Merged with #283. Thanks for the PR!
