### ISSUE TITLE
 Disable the Debug Banner 

### ISSUE THREAD

**Issue by andoriyaprashant** [CCExtractor/ultimate_alarm_clock#29]
### Description

To achieve a cleaner and more refined visual experience, the proposed change is to set debugShowCheckedModeBanner to false in the MaterialApp widget of the Flutter app's main.dart file.

## Before - 
![0cd855e2-5b88-4879-b2b1-f2dfaf7ab20f](https://github.com/CCExtractor/ultimate_alarm_clock/assets/121665385/2e4e94c0-aba5-48d3-af12-e99bd0d6c943)

## After -
![72266e14-624b-41b7-9bda-73b39dc81938](https://github.com/CCExtractor/ultimate_alarm_clock/assets/121665385/202005fe-079e-4893-9475-36d5c22e701f)

**Comment by andoriyaprashant** [comment]
Hello @MarkisDev Please assign me this issue 
Thank you

**Comment by MarkisDev** [comment]
This isn't a bug. The debug banner won't be seen in the release apk, I prefer having the banner.

However, if @NishantSinghal19 thinks we should remove it, then we can go ahead with it.

Closing the issue for now.

**Comment by andoriyaprashant** [comment]
Ok @MarkisDev 👍🏻

**Comment by NishantSinghal19** [comment]
No we need banner during debugging this gets us to differ from the release apk
