### ISSUE TITLE
Feature: Timer App with History Feature

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#292]
### Description 
The app allows users to  view past timers along with their timestamps and dates. Additionally, users have the option to add labels to past timers for better organization and context

## Features:

View Past Timers: Access a history of past timers along with timestamps and dates.
Labeling: Ability to add labels or notes to past timers for categorization and reference.
Auto-Deletion: Past timers are automatically deleted when the user leaves the timer screen, ensuring privacy and efficient memory management.

Please assign this issue to me.

_No response_

**Comment by MarkisDev** [comment]
Are you suggesting to make it so that we can store the previous timers? Similar to how we do it for alarms?

**Comment by Deepanshuigtm** [comment]
Do we have the option to store that history in a database, such as alarms, or should we consider creating a local list that will be cleared once the user is done using the timer? What's your opinion on this?

**Comment by MarkisDev** [comment]
If we want to store something, definitely use a database. However, my question is, why do you want to store timers? As I understand, aren't timer's a one-time thing? If you want something that's longer, you'd use an alarm right?

**Comment by Deepanshuigtm** [comment]
Storing timer history can hold value across different contexts, including sports activities, work-related tasks, or personal productivity.

We will only save this information if the user clicks on 'save,' thereby avoiding the storage of unnecessary data.

If users have the option to save timer data, we can prompt them to fill in details such as time (e.g., 30 seconds), an automatically generated date, labels, comments, etc., and save these details into the database

If this approach doesn't seem practical or intuitive, we might consider leaving out this feature, as it may not be the best idea.
