### ISSUE TITLE
Feature: Manual Time Entry Option in Timer

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#293]
### Description

Currently, the alarm clock application utilizes the TimePickerSpinner for setting timers. However, it would be beneficial to enhance the user experience by providing an additional option for manual time entry using the keyboard.

### Features Proposed
- **Manual Time Entry:** Enable users to enter timer values manually using the keyboard, offering a more flexible and precise input method.
- **Seamless Switching:** Allow users to easily switch between the existing TimePickerSpinner and the new manual time entry mode, providing versatility in timer setup.
- **Edge Case Handling:** Ensure that all edge cases related to manual time entry are handled effectively, preventing any unexpected behavior or errors.

_I want to work on this issue, so please consider assigning it to me._

**Comment by MarkisDev** [comment]
Manual entry is fine, but with #297 I'm worried that it might be too many ways to enter values. Maybe we can do it similar to how we've done it for setting alarms. Assigning to you.
