### ISSUE TITLE
Feature: Improve Timer layout

### ISSUE THREAD

**Issue by AdarshRawat1** [CCExtractor/ultimate_alarm_clock#295]
## Problem: 
The current layout of the timer does not clearly indicate whether the timer being set is in hours, minutes, or seconds. This can lead to confusion for users who are trying to interpret the time.

## Solution: 
This can be done through labels next to the time values i.e. hours, minutes, and seconds.

## Impact: 
This enhancement will improve user understanding and interaction with the timer. It will remove ambiguity and potential confusion about the timer's units, leading to a more user-friendly and effective timer function.

### Screenshots

![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/100958893/ffaaf0c6-301b-4d07-9c86-deac7a619571)
_I would like to work on this Feature_

**Comment by MarkisDev** [comment]
This is a duplicate issue being addressed by #305. Closing for now.
