### ISSUE TITLE
Feature: Add Increment / decrement Button to timer

### ISSUE THREAD

**Issue by AdarshRawat1** [CCExtractor/ultimate_alarm_clock#296]
## Problem: 
The current implementation of the timer input relies on scrolling to select the time. 
This can be time-consuming and imprecise, especially for selecting large amounts of time.

## Solution: 
Introduce increment and decrement buttons to the timer input by adding widget buttons next to the timer input, allowing users to increase or decrease the time value with a single tap.

Just a thought - we can have standard values like +1, +5 , +10 for min section 
using - `IncrementDecrementFormField` widgets

## Impact: 
This enhancement will streamline the process of setting a timer, making it more efficient and precise. It will improve the user experience by providing a more intuitive and quicker way to set the timer

 _I'd like to  implement this feature._

### Screenshots

![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/100958893/889f023e-f7cc-4012-ad70-5b04a7b58e9b)

**Comment by MarkisDev** [comment]
This is fine, but wouldn't it just get confusing with #297? How are you proposing to make them look distinguishable?

**Comment by AdarshRawat1** [comment]
> This is fine, but wouldn't it just get confusing with #297? How are you proposing to make them look distinguishable?

I'm not so sure about this increment feature, as user might want more control by scrolling ( Standard predefined time seems more logical to me). Still, this is a rough draft of how both can be implemented. 

We can either use the card to actually add values. Whichever may seem more logical to you.  
This is a rough layout of I think we can implement this 
![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/100958893/353fd4ff-08ce-41cf-a167-e4c50e32cbc3)

**Comment by MarkisDev** [comment]
It honestly looks very cluttered. We can just stick to standard timer list for now and remove the increment/decrement button. Feel free to open another issue if you think it's necessary :)

**Comment by AdarshRawat1** [comment]
> It honestly looks very cluttered. We can just stick to standard timer list for now and remove the increment/decrement button. Feel free to open another issue if you think it's necessary :)

Agreed 🙌
