### ISSUE TITLE
Feature: Standard list of timers

### ISSUE THREAD

**Issue by AdarshRawat1** [CCExtractor/ultimate_alarm_clock#297]
## Problem: 
Currently, users have to manually input the desired timer duration, which can be tedious and prone to errors, especially for common time intervals.

## Solution: 

- [ ] - Provide a list of standard timer durations (such as 5, 10, 15, 30 minutes) for users to select from. 

 _via_ `dropdown menu` or a `grid of buttons` 
- When a user selects one of these options, the corresponding timer duration is set automatically.

## Impact: 
This feature will simplify the process of setting a timer, reducing user input errors and saving time. 
It will also encourage users to use the application more frequently, as they can easily set timers for their commonly used durations.

  I would like to work on this issue 

## Future plans -
 

- [ ] Allowing user to customize these based on their specific needs.

**Comment by MarkisDev** [comment]
I agree, this would be helpful. Assigning to you.

**Comment by sagarrajgit** [comment]
@MarkisDev My idea in issue #377 was little different, I wanted to show the list of frequent timers in which user can create list of timer, using which user can quickly set timers of their regular activity like reading, meditation, exercise etc. 

UI will be similar to this, on selecting any of the list, time picker automatically shifted to time of that selected timer list now just press the play button.
![1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/fbdcba8d-9027-446a-a589-0da7e0cc7b5b)

UI of add timer will look like this, here user need to select the time and enter the name of timer.
![2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/931f925e-4439-4622-89eb-a32e12729c3a)

**Comment by MarkisDev** [comment]
@sagarrajgit Thanks for explaining it! I've reopened #377. We can continue the conversation there.

@SATVIKSH I'm assigning this to you.

**Comment by SATVIKSH** [comment]
@MarkisDev I have made a design for selecting the preset times. Kindly have a look at it and suggest any changes. We can scroll vertically to select any time and if the time gets selected the border is highlighted.
![issue](https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/e3382982-f523-4ac0-a66a-333cfc227562)

**Comment by MarkisDev** [comment]
@SATVIKSH I think it's better to show a grid of standard times (5,10,15 etc min). This current design will be confusing for a new user. 

Also, we really don't need to worry about letting them add their own times, that will be addressed in #377, this issue is just to show a list of standard times.

**Comment by SATVIKSH** [comment]
@MarkisDev I will do the suggested changes.
