### ISSUE TITLE
Bug: Splash screen with white box in dark mode

### ISSUE THREAD

**Issue by AdarshRawat1** [CCExtractor/ultimate_alarm_clock#300]
## Bug 
Splash image is shown with a white box around it in dark mode 
## desired 
It should blend with the background

p.s. I am not sure if this is a bug or intended.
If it is a bug I would like to fix it.

### Screenshots

[bug 1.webm](https://github.com/CCExtractor/ultimate_alarm_clock/assets/100958893/7f50102e-40ac-48cf-9e04-1b6379938b79)

**Comment by MarkisDev** [comment]
I think this would fall under #265 itself. Closing for now.
