### ISSUE TITLE
Bug: Light mode does not apply to splash screen

### ISSUE THREAD

**Issue by AdarshRawat1** [CCExtractor/ultimate_alarm_clock#301]
## BUG
The light theme option does not apply to splash screen.

## Expected 
Light theme of application should also apply to the splash screen

### Reproduce - 
Enable DARK mode in device (Android).

### Screenshots

[bug rec.webm](https://github.com/CCExtractor/ultimate_alarm_clock/assets/100958893/3c57ac71-ac71-4452-ba13-bc3c958fdc21)

**Comment by MarkisDev** [comment]
Duplicate of #265. Closing for now, let's continue the convo there.
