### ISSUE TITLE
Bug: Alarm Not Ringing While Timer is Running

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#302]
### Description

When the timer is running, the alarm fails to ring. This behavior seems to be a bug as the alarm should sound regardless of whether the timer is active or not.

### Steps to Reproduce
1. Set an alarm.
2. Activate the timer functionality.
3. When the timer is running, wait for the alarm to trigger.

### Expected Behaviour
The alarm should ring according to the configured settings, even if the timer is active. Users should be able to rely on alarms for timely reminders regardless of other ongoing functionalities.

### Actual Behavior
The alarm remains silent when the timer is running, and users do not receive the expected notification.

_I want to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/3bf17d21-b8b6-480c-b098-de18d13ab5df

**Comment by MarkisDev** [comment]
Yeah, this is probably because I've hardcoded the id in `pendingIntent` in `MainActivity.kt`. Might want to add a new parameter for alarm/timer and set a new id accordingly.

Assigning to you.

**Comment by vkprogrammer-001** [comment]
can I work on the issue? if the issue is still open.

**Comment by MarkisDev** [comment]
Feel free to put up a PR @vkprogrammer-001

**Comment by Detective-Khalifah** [comment]
Hi @vkprogrammer-001 ! Are you still working on this? What's your status?
