### ISSUE TITLE
Feature: Add hours,minutes and seconds in timer section

### ISSUE THREAD

**Issue by chinmay7016** [CCExtractor/ultimate_alarm_clock#304]
### Description

Want to create this feature
<img width="383" alt="Screenshot 2024-01-05 at 8 56 06 PM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/75988613/8246abc8-a5b5-4db2-afaf-e3553372c452">

At present it looks like this
<img width="389" alt="Screenshot 2024-01-05 at 9 00 19 PM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/75988613/f3535a84-3e31-4dec-bb06-19580ba21d2b">

**Comment by MarkisDev** [comment]
#305 already addresses this. Closing for now,
