### ISSUE TITLE
Feature: Adding swipeable view

### ISSUE THREAD

**Issue by SATVIKSH** [CCExtractor/ultimate_alarm_clock#308]
### Description

Adding a feature to swipe between alarm view and timer view.

**Comment by AdarshRawat1** [comment]
## Few thing to keep in mind before working on this feature
> The swipe gesture from edge is captured by the menu. 
> #285 PR is implementing swipe to delete 

Implementation will require some feedback from the maintainers.

p.s.
-  We can use Specific Gesture Detectors.
- Might have to move the setting page to the left side in future.

**Comment by SATVIKSH** [comment]
We can restrict delete gesture to right swipe and swipe page with left swipe.

**Comment by MarkisDev** [comment]
Yeah, this could be tricky. @AdarshRawat1's approach should work. I'll assign it to both of y'all, if you get stuck please feel free to ask me! :)

We'll need this view since more features (apart from alarm) is being added to the application.

**Comment by duckcommit** [comment]
I think I will be able to fix this issue @MarkisDev. This is what I am going to do. Limit the swipe to delete to only left to right. I will also add a red background to show that it is being deleted. Will make the pages swipable too.
