### ISSUE TITLE
Feature: addition of motivational quote after every alaram

### ISSUE THREAD

**Issue by chinmay7016** [CCExtractor/ultimate_alarm_clock#312]
### Description

i have added a feature of motivational quote after every alaram, it's always different

https://github.com/CCExtractor/ultimate_alarm_clock/assets/75988613/7f7bdc23-3658-4d1d-be4f-df38d52ebcaa

**Comment by MarkisDev** [comment]
This feature was already merged in with #259. Is there something I'm missing since it seems to work?
