### ISSUE TITLE
Feature: Undo Feature for Swipe-to-Delete Alarm Actions

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#314]
### Description

This feature enhances the alarm management functionality by introducing a swipe-to-delete feature in the user interface. Upon deletion, an undo prompt will appear for a 4-second duration, allowing users to undo the deletion action by simply tapping the "Undo" option. This undo functionality provides a safety net, enabling users to recover accidentally deleted alarms without hassle.

The implementation of this feature involves integrating swipe gestures for alarm deletion and designing a responsive undo prompt that appears immediately after deletion. The timer-based undo prompt will ensure a time-limited window for users to reverse their actions, maintaining a smooth and intuitive user experience while managing alarms.

This enhancement aims to streamline alarm management, reducing the risk of accidental deletions and providing users with a convenient way to recover deleted alarms within a short timeframe.

please assign this to me

**Comment by MarkisDev** [comment]
Sounds great, this will work for multiple delete as well right?

**Comment by Deepanshuigtm** [comment]
#321 will not be needed because if there is undo on delete alarm the #321 will not required we should do any one of them
