### ISSUE TITLE
Bug: Add alarm floating action button has wrong icon

### ISSUE THREAD

**Issue by SATVIKSH** [CCExtractor/ultimate_alarm_clock#315]
### Description

Instead of add icon the FAB displays a hamburger icon which looks inappropriate. I would like to work on this issue.

### Screenshots

![1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/c8c91e2c-1489-483d-bc35-08f86c61c945)

**Comment by MarkisDev** [comment]
This has been fixed in latest commit.
