### ISSUE TITLE
Bug: Inappropriate theme to select language

### ISSUE THREAD

**Issue by SATVIKSH** [CCExtractor/ultimate_alarm_clock#316]
### Description

In dark mode the list displayed to select language is white. I would like to work on this issue.

### Screenshots

![2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/be361986-239d-4fbf-bb3c-302a68d53635)

**Comment by MohamedKamran** [comment]
Can work on this please assign this to me

**Comment by MarkisDev** [comment]
I've assigned this to you @SATVIKSH

**Comment by nikkivirtuoso** [comment]
can i create a pull request ?

**Comment by sagarrajgit** [comment]
@MarkisDev I have not seen any activity in this issue that's why I created a PR.
