### ISSUE TITLE
Bug: Pixels overflow in some widgets for some languages

### ISSUE THREAD

**Issue by SATVIKSH** [CCExtractor/ultimate_alarm_clock#317]
### Description

When we select languages other than english , pixels overflow for some of the widgets. I would like to work on this issue.

### Screenshots

![3](https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/df01a6c9-5b21-4d52-b8b9-8520a9bfd749)

**Comment by MarkisDev** [comment]
Fixed with #325 :)
