### ISSUE TITLE
Bug: Pixel overflow in change language

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#318]
### Description

pixel overflow in "Change Language" dropdown button

### Screenshots

![WhatsApp Image 2024-01-10 at 00 21 01_764d60d8](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/e5e88b1f-e4ae-4697-9252-e0a37f345394)

**Comment by MarkisDev** [comment]
I've assigned this to you.

**Comment by sagarrajgit** [comment]
I have already solved this issue and opened a PR, kindly verify and merge the changes or provide any feedback if necessary.

**Comment by Reetinder932** [comment]
I have made two pull requests for two files in which there is overflow of language please merge those pull requests
