### ISSUE TITLE
Feature: Extending swipe-to-delete 

### ISSUE THREAD

**Issue by rkverma2022** [CCExtractor/ultimate_alarm_clock#321]
### Description
Extending swipe-to-delete
https://github.com/CCExtractor/ultimate_alarm_clock/pull/285 #285 

At times, users may accidentally swipe and delete content they didn't intend to. Therefore, I suggest incorporating a pop-up confirmation message to inquire whether the user genuinely wants to proceed with the deletion.

Hi, I would like to implement it

**Comment by MarkisDev** [comment]
I've assigned this to you

**Comment by rkverma2022** [comment]
https://github.com/CCExtractor/ultimate_alarm_clock/assets/112231455/90b66118-7260-4c34-afd1-3e1c17fc1d57

Hi, 
I have added the mentioned feature, please merge it.

I am looking forward to your feedback, and if any other changes are needed, please let me know.  issue #321

**Comment by rkverma2022** [comment]
@MarkisDev  please merge the pull request, and if you have any suggestions please let me know

**Comment by MarkisDev** [comment]
I've requested for some changes with the associated PR #324 :)

**Comment by its-me-abhishek** [comment]
Hey, can I work on the issue if it is stale?

**Comment by MarkisDev** [comment]
Please feel free to work on it @vkprogrammer-001 @its-me-abhishek
