### ISSUE TITLE
Improvement: Optimization of the Drawer's header

### ISSUE THREAD

**Issue by shrey258** [CCExtractor/ultimate_alarm_clock#322]
### **Description**
Optimizing the Drawer's header

The drawer's header takes up too much place in the drawer. 
I suggest it can be optimized to look better, with smaller font and a minimalistic neat look.
I can fix this issue.

### **Screenshots**
![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91644557/3c4be4e6-c500-4dd5-8fdd-d2622a74e021)

**Comment by MarkisDev** [comment]
I like the way it looks currently, but we're always open to new ideas! I'll assign this to you, please show us an example :)

**Comment by shrey258** [comment]
hi @MarkisDev can you provide me with a transparent png of the ic launcher, that would be a great help, I tried to convert the png into a transparent one but yeah the online image converter destroys it. 

![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91644557/4a577a2a-0fe3-4736-a091-8ba980443679)

**Comment by shrey258** [comment]
Hi @MarkisDev  Pls check if this is good?
### Before
![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91644557/582e834c-e984-4622-a44b-aa95b544cf8e)

### After
![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91644557/40131b7a-15e1-45ee-ad9e-3f61a1de7432)
