### ISSUE TITLE
Bug: Overflow Issue in Settings Widgets when Switching to German, French, or Spanish Language

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#323]
### Description

Bug Description:
When the application language is changed to German, French, or Spanish, an overflow issue occurs within the settings widgets. The overflow affects the layout of certain widgets, causing them to exceed their designated boundaries and disrupt the visual interface.

Expected Behavior:
The application's settings widgets should adapt to different language settings without causing any overflow issues. The UI elements should remain within the specified layout boundaries, maintaining a consistent and visually pleasing interface across various language selections.

Actual Behavior:
Upon changing the language to German, French, or Spanish, certain settings widgets overflow their designated spaces, leading to a disruption in the layout and appearance of the settings screens.

please assign this to me :)

### Screenshots
![WhatsApp Image 2024-01-10 at 1 39 01 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/a48285fd-5b96-481c-aecd-26eadc96dd4d)
![WhatsApp Image 2024-01-10 at 1 39 00 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/602a9fe7-0485-49ec-a259-8087e4f558a7)

**Comment by sagarrajgit** [comment]
I have already solved this and generated PR in issue #317

**Comment by Deepanshuigtm** [comment]
yes but I tried your branch that PR #317 it still ov
![Screenshot 2024-01-10 at 4 35 44 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/25aa13d8-88ab-494b-8b70-7d1c08247a7d)
erflow on small devices

**Comment by sagarrajgit** [comment]
I had accidently sent other file in previous PR, now I have fixed it.

**Comment by sagarrajgit** [comment]
I have rechecked it and didn't find any thing wrong, here is the screenshot where everything is working completely fine, if you still getting same error please provide video of process where you are getting this error.

<img width="959" alt="image" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/df815e1f-1ccd-4071-bf2f-ab70e32ae7d9">

**Comment by Deepanshuigtm** [comment]
yes its fixed

**Comment by sagarrajgit** [comment]
@Deepanshuigtm @MarkisDev, It is verified that the problem is fixed, kindly merge the changes.
