### ISSUE TITLE
Feature: Timer Reset Button

### ISSUE THREAD

**Issue by shrey258** [CCExtractor/ultimate_alarm_clock#328]
### Description

The timer can have a reset button to reset the timer 
I can add this feature.

### Screenshots

![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91644557/3f52758c-e161-439e-af2d-eff408ab9a5d)

**Comment by MarkisDev** [comment]
I've assigned this to you, feel free to ask for help if you get stuck somewhere :)

**Comment by duckcommit** [comment]
I would like to take up this issue @MarkisDev

**Comment by shrey258** [comment]
hi @duckcommit , 
Sorry but I am already working on this one!

**Comment by duckcommit** [comment]
Oh no issues then. Take your time. Do let know if you need any help. Will be glad to help out!!
