### ISSUE TITLE
Bug:  pixel overflow in app bar

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#334]
### Description

When you select Russian as the language, the message 'No upcoming alarms!' in Russian overflows 

### Screenshots

![3](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/89b8d927-33da-4564-8054-f4bd19dafadc)

**Comment by MarkisDev** [comment]
I've assigned this to you
