### ISSUE TITLE
Bug: text alignment issue on home page in German language

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#336]
### Description

When you select German, alignment of the German message of 'Add an alarm to get started' is incorrect

### Screenshots

![1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/9a851a0f-a9f9-4552-bc6e-f5417ab29876)

**Comment by rkverma2022** [comment]
@sagarrajgit are you resolving this bug?

**Comment by sagarrajgit** [comment]
yes

**Comment by rkverma2022** [comment]
Ok, best wishes

**Comment by sagarrajgit** [comment]
actually I had solved this issue and generated PR but forgot to add issue tag that's why PR was not visible.
