### ISSUE TITLE
Add Feature: Add Timer CircularCountDownTimer

### ISSUE THREAD

**Issue by cabdiris** [CCExtractor/ultimate_alarm_clock#343]
### Screenshots

![Screenshot_1705330249](https://github.com/CCExtractor/ultimate_alarm_clock/assets/148750922/53d4854e-2aa1-451b-9d43-707fdebaee51)

![Screenshot_1705331273](https://github.com/CCExtractor/ultimate_alarm_clock/assets/148750922/67ce9bf5-7ee3-445c-bf0e-888e85bfacf7)

_No response_

**Comment by nikkivirtuoso** [comment]
@cabdiris have you completed this task or you have suggested these changes ?

**Comment by cabdiris** [comment]
i complete

**Comment by cabdiris** [comment]
yes i complete this task

**Comment by Hemant-05** [comment]
this looks nice 👍.

**Comment by MarkisDev** [comment]
Closing this since it's a duplicate of #299. We can continue the conversation there.
