### ISSUE TITLE
Bug: Remove the previous "Undo" option before displaying the new one

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#353]
### Description

When swiping to delete multiple alarms simultaneously, the application does not remove the previous "Undo" option before displaying the new one. This behavior can lead to confusion as users may unintentionally trigger the wrong undo action.

### Steps to Reproduce:
1. Swipe to delete one alarm.
2. Quickly swipe to delete another alarm before the previous undo option disappears.

### Expected Behavior
The application should remove the previous "Undo" option when a new alarm is swiped for deletion, ensuring a clear and accurate undo action.

### Current Behavior
The previous "Undo" option persists when swiping to delete multiple alarms simultaneously.

please assign this to me

**Comment by MarkisDev** [comment]
I've assigned this to you.
