### ISSUE TITLE
Feature: New Feature: confirmation Option for Bulk Alarm Deletion

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#355]
### Feature Description:
Introducing a new feature that enhances the user experience when deleting multiple alarms! Now, when users delete alarms in bulk by selecting and holding, a convenient "Undo" option will be available for 4 seconds. This allows users to quickly recover accidentally deleted alarms with ease

### How It Works:
1. Select and hold to delete multiple alarms.
2. A confirmation dialog appears with the option to "Undo" the deletion.
3. The "Undo" option remains available for 4 seconds, providing users with a brief window to revert the deletion.

## Benefits:
1. Prevent accidental data loss by offering a simple and effective undo mechanism.
2. Enhance user confidence when managing alarms in bulk.

The new feature has been implemented to improve user interaction and provide a safety net for users performing bulk alarm deletions.

Please assign this to me :)

**Comment by duckcommit** [comment]
It is a good idea. But then, to delete multiple alarms, a user holds and presses, selects multiple alarms and then hits the delete button. So, I feel like it wouldn't happen by accident. Instead, a suggestion would be to add a confirmation box before deleting in bulk. What do you think?

**Comment by MarkisDev** [comment]
I agree with @duckcommit on this. A confirmation would be better than an undo here.

**Comment by Deepanshuigtm** [comment]
Okay @MarkisDev, I will implement a confirmation box for deleting alarms in bulk. And @duckcommit, thanks for the suggestion  :)
