### ISSUE TITLE
UI/Styling: Red border around snackBar for better visualization

### ISSUE THREAD

**Issue by duckcommit** [CCExtractor/ultimate_alarm_clock#357]
When an alarm is deleted, a snack bar appears with a message and undo option. It looks great, but to make it a little bit better, we can add a red light border to it.

**Comment by MarkisDev** [comment]
We haven't really followed this with the other Snackbars used in different places. I'm closing this for now since it would be inconsistent.

**Comment by MarkisDev** [comment]
We haven't really followed this with the other Snackbars used in different places. I'm closing this for now since it would be inconsistent.
