### ISSUE TITLE
Feature: [Accessibility] -> Changing Time picker in timer page for smooth scrolling and UI redesign

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#362]
### Description

To enhance user interaction in the UI, I suggest replacing the TimePickerSpinner with a NumberPicker when setting timer. The NumberPicker widget offers several advantages, such as a more visually appealing timer selection and a distinct box-like separation while scrolling. This change not only improves the UI but also provides a faster scrolling experience, enhancing overall user interactivity.

https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/4d45fb76-804e-4fa0-aab8-171d0f2c3d77

@MarkisDev If you like this UI and changes then I will generate PR.

**Comment by duckcommit** [comment]
Nice, this looks great!!

**Comment by sagarrajgit** [comment]
thank you

**Comment by MarkisDev** [comment]
Looks great, but it will have to be consistent which means you'll have to make the change for the alarm screen as well. Assigning this to you.

**Comment by sagarrajgit** [comment]
I am ready to do this change for alarm screen

**Comment by MarkisDev** [comment]
Feel free to put up a PR :)
