### ISSUE TITLE
Bug: Pixel overflow in different options

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#363]
### Description

Inside the add or update alarm, there are lot of options in which text overflows in other languages and dialog box which comes after tapping on those options has overflowed in their button.

### Screenshots

![6](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/668e1499-338a-4894-acc5-fa5bb827b7a2)
![5](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/7ef580d3-4221-492c-afc4-b5f5251b73b8)
![4](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/77e243ba-29a0-4088-9861-f186b55c7453)
![3](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/df698704-4f72-45ca-ad6d-955d4e3be162)
![2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/765be971-d936-43c5-acd0-45b924d0d33f)

**Comment by MarkisDev** [comment]
Yeah, adding new languages has brought these overflows. I'll assign this to you. Thanks for the issue!
