### ISSUE TITLE
Feature: Alarm Preview

### ISSUE THREAD

**Issue by duckcommit** [CCExtractor/ultimate_alarm_clock#364]
### Description

When we upload a lot of alarms, at one point, there might be a case where we don't know what a particular tone sounds like. For that reason we will add an alarm preview.

**Comment by superiorsd10** [comment]
Hello @duckcommit 👋
It's great to see you contributing, man! But it would be best to wait for the maintainer to assign an issue to you, and then you can open a PR. Otherwise, if it's not seen as necessary, your PR efforts may be wasted.

**Comment by duckcommit** [comment]
Ah yes @superiorsd10. I will keep that in mind. Felt like an important feature, that is why i decided to open a PR.

**Comment by MarkisDev** [comment]
Sounds like a great idea! Thanks for the PR :)
