### ISSUE TITLE
Bug: The tile color of the selected sound is overflowing

### ISSUE THREAD

**Issue by duckcommit** [CCExtractor/ultimate_alarm_clock#366]
### Description

The selected tile colour is overflowing if more items are in the scroll box.

### Screenshots

![Screenshot_20240120_160529](https://github.com/CCExtractor/ultimate_alarm_clock/assets/22213675/555ddf24-dbec-4d92-aaeb-a179881610a1)

**Comment by MarkisDev** [comment]
Fixed with #359
