### ISSUE TITLE
Feature: Add margin to the snack bar when user swipes to delete alarm

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#370]
### Description

Currently, when the user swipes to delete the alarm on the `HomeView`, the snack bar is stacked at the bottom of the screen which affects the user experience.

So, I think it would be better to give some margin to that snack bar. 

_I want to work on this issue, so please consider assigning it to me._

### Screenshots

**Before**

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/71591a82-a222-4ff4-8d42-0e3624c7d5af

**After**

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/ee66e311-ec3a-4748-b748-52f4f649501e

**Comment by duckcommit** [comment]
Are you referring to Pull Request #358 ? I am waiting for it to get merged.

**Comment by MarkisDev** [comment]
I've assigned this to you.
