### ISSUE TITLE
Bug: The "Hold Gesture" for bulk deleting alarms and the "Swipe to Delete" functionality can run simultaneously

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#371]
### Description

When attempting to use the "Hold Gesture" to initiate bulk deletion of alarms, the "Swipe to Delete" functionality can be triggered simultaneously. This behavior is inconsistent with the intended functionality, as the "Hold Gesture" should exclusively activate the bulk delete feature without interference from other gestures.

### Screenshots:

https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/e9edb1fa-3456-4bd5-abdb-f60088c92a46

### Expected Behavior:

1. The "Hold Gesture" should exclusively activate the bulk delete feature, allowing users to select multiple alarms without interference from the "Swipe to Delete" functionality.
2. when user use Hold gesture to delete bulk alarm then swipe to delete should not be available at that time 

Please assign this to me :)

**Comment by MarkisDev** [comment]
I've assigned this to you
