### ISSUE TITLE
Feature: Show snack bar when the user deletes an alarm through pop up menu

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#372]
### Description

Currently, when the user deletes an alarm through swipe-to-delete functionality, a snack bar is shown informing them about the successful deletion of the alarm. 

But when they delete an alarm through the pop-up-menu, then the same information snack bar is not shown. 

It creates an inconsistency in the user experience. 

I think we should show the snack bar when the user deletes an alarm through the pop-up-menu.

_I want to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/1f34b017-e12e-4729-88c7-6af90a41c7bd

**Comment by Deepanshuigtm** [comment]
this issue already in PR  Remove the previous "Undo" option before displaying the new one #353

**Comment by MarkisDev** [comment]
The undo feature was planned to prevent accidental deletion, it seems unlikely that someone would accidently delete it using the pop-up menu. But I agree that the inconsistency looks off, I'll assign this to you.
