### ISSUE TITLE
Bug: Bugs in add options for selecting days while creating/updating alarm

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#373]
### Description

I have observed many bugs in the `Repeat`tile in the `AddOrUpdateAlarmView`. 

They are as follows:
- `Daily` list tile's checkbox is not responsive.
- On selecting `Weekdays` checkbox, days from Tuesday to Saturday are displayed in the Repeat tile, while on tapping the `Weekdays` tile, Weekdays is displayed in the Repeat tile.
- On tapping the `Custom` list tile, and not selecting any days from the dialog box, the Custom tile's checkbox remains selected even though no day is selected.
- On checking the `Custom` list tile's checkbox, no dialog box appears to select custom days for the alarm. 
- Once selected the `Custom` list tile's checkbox, you can't toggle it.

I would like to resolve them all. 

_I want to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/286865dc-5fbf-4722-a7c2-8a7caa01c27a

**Comment by MarkisDev** [comment]
To add onto this, I think those three options (daily, weekdays and custom) should be mutually exclusive. I also think instead of making custom a checkbox, it should probably have an arrow that leads to the dialog.
