### ISSUE TITLE
Bug: Error text not being show when user enters only whitespaces in API text field

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#374]
### Description

Currently, when the user enters only whitespaces in the API key text field in `SettingsView`, the error text is not shown. 

It should be shown when the user doesn't enter anything (which is shown) as well as when they only enter whitespaces. 

_I want to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/2c8bbf0c-3cc9-4af0-893e-daac21f9db1f

**Comment by MarkisDev** [comment]
I've assigned this to you
