### ISSUE TITLE
Bug: Error text being shown in the API key textfield when user opens the dialog again

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#375]
### Description

Currently, when the user enters nothing in the text field and tries to press the `Save` button on the `API Key` dialog, it shows an error text. 

But when the user closes the dialog, and opens it again, the error text is still being shown. 

Once the dialog is closed, the error text should not be shown. 

_I want to work on this issue, so please consider assigning it to me._

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/bb2e6a30-d6af-454f-81e1-0a0200c83b0f

**Comment by MarkisDev** [comment]
I've assigned this to you
