### ISSUE TITLE
Feature: Customizable Undo Duration

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#378]
### Description

Undo Duration allows users to customize the duration of the undo option. By default, the undo duration is set to 4 seconds, but with this new feature, users have the flexibility to adjust it according to their preferences.

The "Undo Duration" setting allows users to tailor the time window for undoing actions. By default, the duration is set to 4 seconds, striking a balance for typical use cases. Users seeking a personalized experience can easily adjust the undo duration to better suit their workflow.

### Usage:
1. Navigate to the project settings.
2. Locate the "Undo Duration" option.
3. Adjust the duration using the provided controls.
4. Changes take effect immediately, reflecting the user's preferred undo duration.

### Default Setting:
Undo Duration: 4 seconds

### Benefits:
- Flexibility: Users can adapt the undo duration to match the pace and complexity of their tasks.
- Efficiency: Tailoring the undo duration enhances productivity for various use cases.
- User-Centric: Providing customization options contributes to a user-friendly experience.

Please assign this to me :)

**Comment by MarkisDev** [comment]
I've assigned this to you
