### ISSUE TITLE
Bug:24-hour format didnt change in alarm format time

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#379]
### Description

When switching to the 24-hour time format, the application still displays the time in an AM/PM format, failing to reflect the intended change. This behavior is inconsistent with the selected time format and can potentially cause confusion for users relying on the 24-hour time representation.

### Steps to Reproduce:

1. Open the application settings.
2. Navigate to the time format preferences.
3. Switch to the 24-hour time format.

###  Expected Behavior:
 The application should display the time exclusively in the 24-hour format after the user selects it in the settings.

### Actual Behavior:
Even after selecting the 24-hour format, the application continues to show the time in the AM/PM format.

https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/b05fa674-c81d-4add-9b68-a7c705f9b958

Please assign this to me :)

**Comment by MarkisDev** [comment]
I've assigned this to you

**Comment by codesage01** [comment]
may i work on this if @Deepanshuigtm  is not working @MarkisDev .

**Comment by JangamRuthvik** [comment]
i don't see that bug anymore was the issue solved and merged?

**Comment by MarkisDev** [comment]
Closing this since the issue seems to be resolved now.
