### ISSUE TITLE
Bug: End Drawer mismatch

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#381]
### Description

UI of alarm screen and timer screen is different.

### Screenshots

![1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/7fd9016e-37ab-4558-867d-aa97523f0d10)
![2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/d8d5ed26-9eec-4283-81d5-57a747f220c5)

And the is some pixel overflow in updated drawer
<img width="216" alt="Screenshot 2024-01-22 233349" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/702af3ec-4927-44f9-a8a0-8673980917df">

**Comment by Kaps61929** [comment]
please assign this issue to me.

**Comment by sagarrajgit** [comment]
I can't assign you but you can work on this issue

**Comment by MarkisDev** [comment]
I've assigned this to you @Kaps61929
