### ISSUE TITLE
Bug: "StopwatchController not found" on the StopWatch Tab

### ISSUE THREAD

**Issue by keyurgit45** [CCExtractor/ultimate_alarm_clock#386]
### Description

When the user clicks the StopWatch tab, the "StopWatchController not found" error is shown. Due to this, the user cannot access the app's stopwatch feature. I want to work on this issue.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/75253653/6e1e0518-ee26-41c8-be8c-422b43d79f49

**Comment by MarkisDev** [comment]
This has been already been fixed with my latest commit.
