### ISSUE TITLE
Feature: Enforce trailing commas for consistent dart code style

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#389]
#### Problem

Currently, contributors may accidentally omit required trailing commas in Dart code, leading to inconsistencies in code style.

#### Proposal

We can integrate a pre-commit hook using `pre-commit` to automatically check for and enforce the inclusion of required trailing commas before each commit. This will help maintain a consistent code style and enhance code readability. 

#### Steps To Be Followed

1. We have to ensure that each contributor has `pre-commit` installed on their local machines. If not, this can be achieved with a simple `pip install pre-commit` command. 

2. Add a `.pre-commit-config.yaml` file to the repository.

3. Contributors run `pre-commit install` once to install the pre-commit hooks in their local repositories.

4. With the proposed pre-commit hook in place, contributors will automatically undergo a check for trailing commas before each commit. If issues are detected, the commit will be blocked until addressed. 

#### Expected Outcome

The integration of this pre-commit hook will enhance the project's code quality by ensuring that all contributors adhere to the required trailing comma conventions, promoting consistency and readability. 

_I want to work on this issue, so please consider assigning it to me._

**Comment by MarkisDev** [comment]
I've assigned this to you
