### ISSUE TITLE
Bug: Add other languages for pedometer option

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#392]
### Description

Currently, you can see the Pedometer option(text, info, dialog box) only in English after selecting any language. It is good to change the options(text, info, dialog) based on the selected language.

**Comment by Kaps61929** [comment]
can I work on this issue?

**Comment by MarkisDev** [comment]
Feel free to put up PR @Kaps61929 :)

**Comment by Kaps61929** [comment]
sure sir
