### ISSUE TITLE
Bug: Google Sign In state not persisting

### ISSUE THREAD

**Issue by keyurgit45** [CCExtractor/ultimate_alarm_clock#396]
### Description

After successful Google sign-in, the app is not able to persist the login state. Due to this, the shared alarm feature is disabled.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/75253653/6f81e716-1f77-44c5-bb27-961217f54646

**Comment by keyurgit45** [comment]
when I click on the Sign-in with Google button, it throws an exception 

> PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

The sign-in function returns false instead of null. So below code shows a success dialog.

```
bool? isSuccessfulLogin = await controller.loginWithGoogle(); 
     if (isSuccessfulLogin != null) {
            Get.defaultDialog(```

**Comment by yaviral17** [comment]
you can use your own firebase project for testing

**Comment by MarkisDev** [comment]
This should be occurring because the state isn't changed when you login using the dialog in `AddOrUpdate` screen. 

Also, it's better for you to setup your own firebase environment to work on this :)
