### ISSUE TITLE
Bug: Parent data widget error

### ISSUE THREAD

**Issue by Kaps61929** [CCExtractor/ultimate_alarm_clock#398]
### Description

Incorrect use of the Parent Data Widget is shown when we run in debug mode.

When navigating to the 'Add' or 'Update' alarm screen, it reappears under the following conditions:

1)Any options are selected in the modal sheet that appears from the repeat tile.
2)The weather permission dialogue box appears.
3)The 'Enable Shared Alarm' dialogue box appears.

I want to work on this issue, so please consider assigning it to me.

### Screenshots

<img width="533" alt="issue_toggle" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/115138974/ebd2cab1-ca30-4184-b9b0-b3daaf641bcb">

**Comment by MarkisDev** [comment]
I've assigned this to you.

**Comment by MarkisDev** [comment]
This should now be resolved.
