### ISSUE TITLE
UI Enhancement: Improved Alarm Settings Interface

### ISSUE THREAD

**Issue by rishi115** [CCExtractor/ultimate_alarm_clock#4]
I propose replacing the current icon-tap in the "Add Alarm" features with ListTile components. This change will enhance user experience by providing a more interactive and informative interface for selecting alarm settings.

https://github.com/CCExtractor/ultimate_alarm_clock/assets/69479714/691f46b6-1ab4-4080-8dd7-167642d84100

https://github.com/CCExtractor/ultimate_alarm_clock/assets/69479714/48dfcf73-23b5-4a53-b058-cff585bbbe44

**Comment by MarkisDev** [comment]
Yeah, I've been wanting to do that as well. I shall assign the issue to you :)

**Comment by rishi115** [comment]
Should i do this to every ListTile ?

**Comment by MarkisDev** [comment]
That would be favorable, yes.

**Comment by rishi115** [comment]
pls review my pr #8 .
I wasn't able to link my Google account, so I couldn't add the ONTAP to the alarm ID.
@MarkisDev

**Comment by MarkisDev** [comment]
Merged #10
