### ISSUE TITLE
Feature: Implement Splash Screen

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#40]
### Description

I have a feature request that I would like to implement in this application. It is about implementing the `splash-screen` in this application. For now, whenever the user opens the application, he/she is redirected to the `addOrUpdateAlarm` view (home screen). But that impacts the UX of the application. So my idea is to implement a basic splash screen adapted to the overall UI of the application. If possible, please assign me this issue. 

Here I'm attaching the Figma file of the design:-
https://www.figma.com/file/tnIt6I156sGbNY5jpAL5kq/ultimate-alarm-clock?type=design&node-id=0%3A1&mode=design&t=zf0EaQnP8PcV5OSf-1

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/f2ff5ba5-9452-452e-b830-2db7ec9f2932

**Comment by MarkisDev** [comment]
I'm okay with a splash screen. Would be better with the logo as well! I'll send it to you over Slack :)

Could you elaborate on why you think it impacts user experience? As per my understanding, they'll still be redirected to the home screen after the splash screen or am I missing something here?

**Comment by superiorsd10** [comment]
Sure! I'll design and implement it with the logo. 

I think the splash screen will overall increase the user experience of the app. It'll be visually appealing and engaging to the users. Also, it'll help to mask the loading time of the app.
