### ISSUE TITLE
Bug: UI Overflow Bug When Changing Language

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#402]
### Description

When changing the language settings and attempting to put an alarm on hold to delete it, the top navigation user interface (UI) experiences overflow issues. This results in a display problem where elements extend beyond the expected boundaries, making it challenging for users to interact with the application effectively.

![WhatsApp Image 2024-01-29 at 8 34 46 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/c87a9160-9412-46f9-a666-6f7d49b0c330)

Please assign this to me

**Comment by MarkisDev** [comment]
I've assigned this to you

**Comment by KSURESHCHANDRAREDDY** [comment]
@MarkisDev can i work on this..
