### ISSUE TITLE
Bug: Translation Bug: Undo Texts Not Updating Language When Swiping to Delete Alarms"

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#403]
### Description

When swiping to delete an alarm, the undo text messages, such as "Alarm deleted" and "The alarm has been deleted," are not being properly translated into other languages. and also also open whether map Api text not converts to another languages
![WhatsApp Image 2024-01-29 at 8 41 04 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/426596f0-20da-4e09-a69f-a49f13c5ec88)
![WhatsApp Image 2024-01-29 at 8 50 45 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/351d8112-ad45-4a92-857f-a716d27107c3)

please assign this to me

**Comment by Kaps61929** [comment]
I noticed the 'Open Weather Map API' within the translation folders for Spanish, German, Russian, and French. I feel It was consistently kept in English internationally. For addressing other potential issues, I recommend a quick solution. Add translations for text using key-value pairs in the translation file for each language. Then, utilize the .tr getter wherever the text is used.

**Comment by Kaps61929** [comment]
@Deepanshuigtm, there is another translation bug. When you change the language, the 'Change Language' dropdown does not get translated also solve this you are assigned this issue.

**Comment by MarkisDev** [comment]
OpenAPI has been left untouched on purpose. Change language has been fixed with #397 

I've added translations for undo feature in the latest commit, so closing this for now.
