### ISSUE TITLE
Bug: Get default dialog 

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#405]
### Description

When I get into any alarm tile and try to get out of it then a dialog box pop up even after changing nothing. Instead of that it should show a pop message only when I changed anything and didn't update or save.

## Video

https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/87027f7a-d94b-4d05-b3a2-1f8769f7cb46

**Comment by MarkisDev** [comment]
I've assigned this to you.

**Comment by keyurgit45** [comment]
If this is up for a grab, I would like to work

**Comment by beraSayantan** [comment]
@MarkisDev, this issue has not yet been solved. Please assign me this; I will work on it.

**Comment by nidhin29** [comment]
can i work on this issue?

**Comment by saurav0523** [comment]
@MarkisDev can i work on this issue

**Comment by MarkisDev** [comment]
@keyurgit45 @beraSayantan @nidhin29 @saurav0523 Anyone of you can put up a PR, if it fixes the issue we'll merge it in.

**Comment by saurav0523** [comment]
@MarkisDev ok

**Comment by AliAoun** [comment]
@MarkisDev Since others are already assigned, can I work on this issue too?
