### ISSUE TITLE
Bug: Upgrade bottom navigation

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#407]
### Description

Issues:
1. Stopwatch icon and timer icon look similar
2. When I am on alarm page and want to get into timer page then it goes through stopwatch page(which means first it goes to stopwatch page and then timer page) works similarly when you do this in reverse order, instead of that it jumps directly to the page which I selected.
3. If I am on timer screen then close the app and reopen it, now I am on alarm screen but bottom navigation still show timer screen, similar problem for stopwatch.

Proposed Features:
- Selected and unselected icons should be different(unselected icons should be void and selected icons should be filled).
- Unselected Icon colour should be unselected text colour.

### Screenshots

Issue 1.
![1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/7e93f475-9d79-4dd2-84bd-d9720c7802aa)

Issue 2.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/dffd9e6d-939f-4c21-92a1-68cdc05e3364

Issue 3.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/6da9002e-fd67-4d95-a088-8a477a1f0299

**Comment by MarkisDev** [comment]
I've assigned this to you.

**Comment by sagarrajgit** [comment]
![Screenshot 2024-02-06 175725](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/edb7e037-34a4-4815-a9a8-1b159f6ab72e)

@MarkisDev Why is App Lifecycle used, if it is used to save the last page index when the app got inactive or paused and whenever the user opens back from the recent app it should show the last page and its index then I think these things OS can handle itself. After reading the article about this I have understood that it is used in message app when a user switches their apps(now running in the background) then this user seems offline to other users.

**Comment by MarkisDev** [comment]
When the alarm rings when you're on Stopwatch/Timer screen, the tab index will be lost. We monitor the lifecycle to take the user back to the same tab he was on after dismissing the alarm.

> ![Screenshot 2024-02-06 175725](https://private-user-images.githubusercontent.com/78961406/303210742-edb7e037-34a4-4815-a9a8-1b159f6ab72e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NDMxMTAsIm5iZiI6MTcwNzQ0MjgxMCwicGF0aCI6Ii83ODk2MTQwNi8zMDMyMTA3NDItZWRiN2UwMzctMzRhNC00ODE1LWE5YTgtMWIxNTlmNmFiNzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDAxNDAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYTlmMGEzMzg4N2MwMDdhM2Y5ZGM5NDM3OTVmZjdlMTllNTcyZjFmMGEyZWU5ZjAwYjE1MTBjYTVmZmQ3NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r3-LzpblIXXQBMkfj4QqGkU8Q2_9xNiIK3_iNzbAY6s)
> 
> @MarkisDev Why is App Lifecycle used, if it is used to save the last page index when the app got inactive or paused and whenever the user opens back from the recent app it should show the last page and its index then I think these things OS can handle itself. After reading the article about this I have understood that it is used in message app when a user switches their apps(now running in the background) then this user seems offline to other users.

**Comment by Wreck-X** [comment]
Hey is this issue still being worked on id like to give it a try if possible.

**Comment by sagarrajgit** [comment]
@Wreck-X You can try, no problem
