### ISSUE TITLE
Bug: Shakey Counter

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#408]
### Description

When you start the stopwatch, the counter shakes continuously similar problem with timer counter. These should be fixed on their position.

## Video

https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/0383866d-2d0a-41f4-b9ba-2c1e87a94534

**Comment by MarkisDev** [comment]
Feel free to work on this!
