### ISSUE TITLE
Bug: Can upload duplicate ringtone file

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#416]
### Description

In choose ringtone section I can upload the same file multiple times and on selecting one of that files all files with the same name get selected. The ideal operation would be whenever I uploaded a file which is already present then it should not be added and show a snack message.

https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/6e823d8f-810e-470c-b462-7d3223832465

@MarkisDev In the current main branch selected ringtone is still visible outside the container but I solved this problem in the issue #359

**Comment by MarkisDev** [comment]
You can work on the duplication issue. #359 code should now be back into the codebase with the latest commit :)

**Comment by sagarrajgit** [comment]
I have changed all the things as you told
