### ISSUE TITLE
Feature: Enable Haptic Feedback on Buttons

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#42]
### Description

I have a feature request that I would like to implement in this application. It is about giving the user an option in the `Settings` page to enable `HapticFeedback` on all the buttons (IconButton, TextButton, FloatingActionButton, etc.), and Radio Widget. It'll be enabled by default when the user installs the application. However, users will have the choice to disable it as per their convenience and preference through the `Settings` page. 

### Why do we need HapticFeedback?

When I was using this application, I pressed the FAB to add the alarm, and I didn't feel anything, it took some milliseconds to load the `AddOrUpdateAlarm` view. At that point, I felt that it would be better if you got some feedback (vibrating) on pressing these buttons. It'll enhance the user experience to some extent. Also if the user doesn't feel that way, then they can disable it any time. 

I'm attaching a screenshot of the design of the `Updated Setting Page`. If possible, please assign me this issue. 

### Screenshots

<a href="https://ibb.co/2vXkwXc"><img src="https://i.ibb.co/D93RN3w/haptic-feedback-design.png" alt="haptic-feedback-design" border="0" width="360" height="730"></a>

**Comment by MarkisDev** [comment]
This sounds like a great idea! I'll assign this to you :)
