### ISSUE TITLE
Styling: Bottom Nav not visible in Light Mode

### ISSUE THREAD

**Issue by duckcommit** [CCExtractor/ultimate_alarm_clock#442]
### Description

If you check the bottom nav, when it is selected, the readability of the green font is less. So, how about we add a text border/stroke to the selected text? In this case, let's add a very thin black border. I am suggesting a thin border because the fluorescent green is the entire essence of the app. So, the expected output would be to have a green font with a slight black border/stroke.

Inorder to match this in dark mode, we can give a white thin border to the selected bottom nav option. 

### Screenshots

![Screenshot_20240212_231751](https://github.com/CCExtractor/ultimate_alarm_clock/assets/22213675/12963cfa-f973-4ebb-8f51-153a2b34fe5b)

**Comment by nidhin29** [comment]
can i work on this issue?

**Comment by duckcommit** [comment]
I was planning to work on it @Adiii1436 & @nidhin29. But it's okay. First, wait for the maintainer to decide whether it is a good idea or not,. After that, one of you can work on it. 
Meanwhile both of you can set up your dev environment.

**Comment by MarkisDev** [comment]
I understand what you mean, but we'll need a preview to be sure that it actually suits the theme and doesn't look too odd.
