### ISSUE TITLE
Bug: Unable to update an offline alarm to a shared alarm.

### ISSUE THREAD

**Issue by keyurgit45** [CCExtractor/ultimate_alarm_clock#443]
### To reproduce the issue, follow these steps:

1. If your Google account is linked, unlink it.
2. Create an offline alarm if you haven't already done so.
3. Tap on the created alarm and select the shared alarm section.
4. Link your Google account through the dialog box that appears.
5. Click on the update button.
6. The alarm will be updated, but an error will occur. Additionally, you won't be able to turn off the alarm.

There seems to be a problem with the record that has been created in Firebase. It appears that the ownerId parameter is missing.

I am willing to work on this issue.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/75253653/ef0a5c0d-d804-4e85-9d2b-d74f0ee8dd9c

**Comment by MarkisDev** [comment]
I've assigned this to you
