### ISSUE TITLE
Refactor: Repeat Tile Methods Parameters

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#447]
Currently, the `buildDailyTile`, `buildCustomDaysTile`, and `buildWeekdaysTile` methods in `repeat_tile.dart` requires `AddOrUpdateAlarmController`, and `ThemeController` which are unnecessary as they are already available in the class scope. 

_I want to work on this issue, so please consider assigning it to me._

**Comment by vkprogrammer-001** [comment]
if no one is working on the issue.  can I work on the issue? please assign this to me

**Comment by MarkisDev** [comment]
I've assigned this to you @superiorsd10
