### ISSUE TITLE
Bug: Compatibility Issue with Firebase/CoreOnly on iOS Installation for Mac M1

### ISSUE THREAD

**Issue by oops-shlok** [CCExtractor/ultimate_alarm_clock#448]
### Description

When I am trying to install the app in iOS simulator on Mac M1, I face compatibility issues due to CocoaPods struggling with version compatibility. This discrepancy between Podfile.lock and Podfile versions causes dependency conflicts, hindering smooth integration. Please assign me to this issue so that I can work on this and fix it.

### Screenshots

<img width="1679" alt="Screenshot 2024-02-15 at 7 09 05 PM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/83498152/80874cba-5b47-460c-b105-bfc103e99530">

**Comment by oops-shlok** [comment]
@MarkisDev can u please assign me this issue?

**Comment by MarkisDev** [comment]
The application has issues with iOS since we're using native calls to schedule alarms. It should be a good idea to fix this, but we'll have to figure out a way to make alarms work on iOS as well.
