### ISSUE TITLE
Bug: Alarm ringtone continues to play even after pausing

### ISSUE THREAD

**Issue by nidhin29** [CCExtractor/ultimate_alarm_clock#455]
### Description

Go to the add an alarm page and in that if you go to choose ringtone and play the default ringtone then it continues to play even after stopping it. Even if you go to home screen it continues to play.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/131900819/52ddc520-ff0b-463a-bb8a-18a72b915015

**Comment by saurav0523** [comment]
@nidhin29 i want to work on this issue. can you please assign me

**Comment by nidhin29** [comment]
@saurav0523 Actually, I was waiting for this issue to be assigned to me, I want to  work on it just waiting for  the approval

**Comment by nidhin29** [comment]
@MarkisDev can i work on this

**Comment by MarkisDev** [comment]
@nidhin29 I've assigned this to you
