### ISSUE TITLE
Feature: Label is not present at active alarm and disabled alarm in the main alarm list.

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#46]
### Description

I think the label should be there on the main alarm list.
There is only one way to view the label, when you click on the existing alarm, where on label edit you can view as well as edit. 

So I added a label option on the active and disabled alarm(if the user already added a label).

Here are the Screen Shots of before and after:-

### Screenshots

before:-
![im1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/042a58b4-c7b5-484c-b9b5-891d5b3d1973)
![im2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/2c8e8f12-e88c-4a55-9949-87ea02ef8772)

After adding:- 
![WhatsApp Image 2023-09-03 at 7 20 31 PM](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/88590e1b-e712-4676-b6d6-cb034c80c862)

**Comment by MarkisDev** [comment]
I agree that we should probably show labels on the alarms, I haven't done it so far because I couldn't find a good UI design to implement it.

I personally still don't like the way label is shown now as well. Will look odd when the alarm is set to repeat on certain days.

Could you come up with a better design?

**Comment by sameermansoori1** [comment]
> I agree that we should probably show labels on the alarms, I haven't done it so far because I couldn't find a good UI design to implement it.
> 
> I personally still don't like the way label is shown now as well. Will look odd when the alarm is set to repeat on certain days.
> 
> Could you come up with a better design?

yes sure.

**Comment by sameermansoori1** [comment]
@MarkisDev 
Have a look, I think it looks more classic now, other than the past one which looks odd to you.
![Screenshot_20230904_124036](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/555d15ca-ef72-49b2-b431-ca0a94cfa7ec)

**Comment by MarkisDev** [comment]
I think the primary shade of green and non-bold text looked better. Let's go with that for now, if anyone has a better design idea then we'll see.
