### ISSUE TITLE
Bug: Overflow in dialog box of Weather Condition field of AddOrUpdateAlarm

### ISSUE THREAD

**Issue by nidhin29** [CCExtractor/ultimate_alarm_clock#464]
### Description

Steps to reproduce:

- Go to AddOrUpdateAlarmPage and then click Weather Condition Field a dialog box will come and in that there is some overflow towards right

### Screenshots

![Screenshot (80)](https://github.com/CCExtractor/ultimate_alarm_clock/assets/131900819/cd6a19a0-2628-43cb-87b1-ca6f1b512536)

**Comment by AmrAbdElHamed26** [comment]
@MarkisDev can You assign me this issue ?

**Comment by nidhin29** [comment]
@AmrAbdElHamed26 I have fixed the issue just waiting for the approval

**Comment by MarkisDev** [comment]
I've assigned this to you @nidhin29
