### ISSUE TITLE
Feature: add disable option to QR code challenge

### ISSUE THREAD

**Issue by keyurgit45** [CCExtractor/ultimate_alarm_clock#473]
### Description

there is no straightforward way to disable the QR code challenge once enabled. However, it automatically disables when we click on "retake" and instead of taking a picture of the new QR code, we click outside the camera view and exit the dialog. Nevertheless, the QR values do not change in this process.

What can we do?
1. Introduce a new button "Disable" to disable the challenge by setting `isQrEnabled.value `to false and `qrValue.value` to an empty string. 
2. do not change the `qrValue` and  `isQrEnabled` when the user exits the dialog after clicking the on retake.

### Screenshots

| Before | After |
|-----------|---------|
|![Screenshot_20240229-184428](https://github.com/CCExtractor/ultimate_alarm_clock/assets/75253653/f0d56da7-3a25-4755-983c-10328bd2cdd8) | ![Screenshot_20240229-190136](https://github.com/CCExtractor/ultimate_alarm_clock/assets/75253653/ccb00c5b-32fe-499c-92dc-f410cd0988e2)|

I am willing to work on this feature.

**Comment by MarkisDev** [comment]
Makes sense, I've assigned this to you.
