### ISSUE TITLE
Feature: Enhance Timer Notification Options in Ultimate Alarm Clock App

### ISSUE THREAD

**Issue by vkprogrammer-001** [CCExtractor/ultimate_alarm_clock#479]
### Description

**Description:**
The Ultimate Alarm Clock app currently lacks a comprehensive notification system when a timer reaches its end. To improve user experience, we propose the following enhancements:

1. **Timer Completion Notification**:
   - When a timer expires, display a notification to alert the user.
   - The notification should indicate that the timer has finished.

2. **Notification Actions**:
   - Include two actionable buttons within the notification:
     - **Dismiss**: Allows the user to dismiss the notification without taking any further action.
     - **Restart**: Enables the user to restart the timer directly from the notification.

By implementing these features, users will have better control over their timers and a more intuitive experience with the Ultimate Alarm Clock app. 🕒🔔

**want to work on the issue:**
yes. please assign this issue to me

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/143318563/946afe94-7845-412f-9528-769c4709dd56

**Comment by vkprogrammer-001** [comment]
@MarkisDev please this issue to me

**Comment by MarkisDev** [comment]
This seems like an extension of #294. Notification for completion is necessary, so I'll assign this to you.
