### ISSUE TITLE
Feature: Change the ringtone

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#48]
Currently the user can't change the ringtone for the alarm
I was thinking of adding a feature why which the user can achieve this functionality

**Comment by MarkisDev** [comment]
Please go for it as discussed over Slack :)

**Comment by cfsmp3** [comment]
> Please go for it as discussed over Slack :)

What slack channel is used for this?

**Comment by MarkisDev** [comment]
Ah, we discussed this over DM's! My bad, I'll move the discussion to the assigned channel 😬

**Comment by ykhan2476** [comment]
If possible, please assign me this issue.

**Comment by MarkisDev** [comment]
@ykhan2476 I don't mind assigning this to you, if @BrawlerXull is no longer working on it :)

**Comment by tavkeer** [comment]
Does this feature still needs to be done

**Comment by MarkisDev** [comment]
I've assigned this to @tavkeer and @ykhan2476. Please let me know if you get stuck somewhere, we can discuss over Slack in the public channel :)

**Comment by tavkeer** [comment]
hey there is a method in the package used to play the alarm sound known as the "FlutterRingtonePlayer.playRingtone()"
but through this the alarm sound is same as the ringtone of the phone is it ok or you are looking for something else?
<img width="488" alt="Screenshot 2023-10-05 at 3 13 51 PM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/105163810/37c49554-6d94-4e5e-bfc2-cbee91a251ed">

**Comment by tavkeer** [comment]
If it's ok I shall make a PR regarding this

**Comment by MarkisDev** [comment]
@tavkeer We need a solution that will allow users to set custom ringtones :/

**Comment by tavkeer** [comment]
Ok I'll work on that

**Comment by MarkisDev** [comment]
Hmm, using an audio player in the ring screen does sound like a possible solution. We'd have to make it possible for the user to choose their file though - maybe we could show some common alarm sounds as well :D

**Comment by superiorsd10** [comment]
Hey @MarkisDev 👋
As far as I've understood going through this conversation, the user will be able to select any audio file from their local storage and set it as their alarm tone. Also, we'll give them some options in the app itself, to select from. 

We can fetch the default alarm ringtones that come in the phone pre-installed, and show them in the app. I think as you said implementing it through MethodChannel seems a good option. 

I would love to contribute to this issue. So can you please assign it to me?

**Comment by tavkeer** [comment]
@MarkisDev 
I will update the custom ringtone for every alarm as soon as possible and also disintegrate the hive and use the default local storage for that
