### ISSUE TITLE
Bug: Error after dismissing an alarm : "type 'bool' is not a subtype of type 'AlarmModel?'

### ISSUE THREAD

**Issue by AryanSarafDev** [CCExtractor/ultimate_alarm_clock#484]
### Description

After an ongoing alarm is dismissed the error screen pops up with the message "type 'bool' is not a subtype of type 'AlarmModel?'

### Screenshots

![Bug](https://github.com/CCExtractor/ultimate_alarm_clock/assets/96824236/1ce920d1-ed0c-4b70-a139-aeb842ae23d3)

**Comment by AryanSarafDev** [comment]
Hi @MarkisDev! Can you assign this issue to me?

**Comment by MarkisDev** [comment]
Fixed with #485
