### ISSUE TITLE
Bug: Overflow in a timer screen with small mobile phones 

### ISSUE THREAD

**Issue by AmrAbdElHamed26** [CCExtractor/ultimate_alarm_clock#486]
### Description

Steps to reproduce:
1- run the app in a small mobile , if you don't have you can use device_preview package then select small mobile in android or ios
2- go to timer screen and press floating action button 

### Screenshots

![photo_2024-03-03_15-05-16](https://github.com/CCExtractor/ultimate_alarm_clock/assets/86882938/ad5ad376-d8cb-4dbb-83aa-d602d380f28e)

**Comment by AmrAbdElHamed26** [comment]
@MarkisDev i am ready to solve this issue , can you assign me this issue?

**Comment by mohnishdeshpande** [comment]
I am also down to work on this!

**Comment by AmrAbdElHamed26** [comment]
@mohnishdeshpande  I have fixed the issue just waiting for the approval to push changes

**Comment by MarkisDev** [comment]
Fixed with #493
