### ISSUE TITLE
Feature: Apply Material 3

### ISSUE THREAD

**Issue by mohnishdeshpande** [CCExtractor/ultimate_alarm_clock#489]
### Description

The current implementation doesn't make use of material3 widgets, which are visually more aesthetic that the legacy ones.
The feature would require to tweak other bits of the current implementation, for e.g. upon using material3 the toggle buttons don't go well.
The change would really add to the pleasant experience of the app.

**Comment by mohnishdeshpande** [comment]
@MarkisDev I can work on this, it'd be great if you can assign me this.

**Comment by MarkisDev** [comment]
We decided to disable material3 because it was affecting the entire application's look and feel. #155 tried to fix the switch colors, but it wasn't very appealing. Closing for now.
Ref #184.
