### ISSUE TITLE
Bug: Overflow Issue When Deleting Alarms

### ISSUE THREAD

**Issue by vkprogrammer-001** [CCExtractor/ultimate_alarm_clock#495]
### Description

**Steps to Reproduce:**

1. Open the Ultimate Alarm Clock app.
2. Set up alarms.
3. Long-press on an alarm to select it for deletion.
4. Now you will see an overflow issue at the top right corner of the screen.

### Screenshots

<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/143318563/1af7dd2f-8b55-4bfb-9c23-c20c1f601a8e" height="600px" weight="300px"></br>

**Device:**
 Pixel 3a API TiramisuPrivacySandbox 2
**android version:** 14

**Comment by AyushGupta11442** [comment]
hello @vkprogrammer-001  
i want  to work on this issue. can you please assign it to me ?

**Comment by vkprogrammer-001** [comment]
@AyushGupta11442 I am working on this issue. if I am not able to solve it, you can work on the issue.

**Comment by Biky2** [comment]
Hello @vkprogrammer-001 
When I run this app on my emulator I don't faced this error, it seems like the error has been fixed

**Comment by vkprogrammer-001** [comment]
@Biky2 try with this: 
Pixel 3a API TiramisuPrivacySandbox 2
android version: 14
