### ISSUE TITLE
Bug: Request notification permission on iOS is not setup properly.

### ISSUE THREAD

**Issue by 0xharkirat** [CCExtractor/ultimate_alarm_clock#498]
### Steps to get this error:
only on iOS devices.
1. Comment this code out from the function **checkOverlayPermissionAndNavigate()** in file **add_or_update_alarm_controller.dart** to prevent permissions error mentioned in issue #497 
```
              // Request overlay permission
              if (!(await Permission.systemAlertWindow.isGranted)) {
                final status = await Permission.systemAlertWindow.request();
                if (!status.isGranted) {
                  debugPrint('SYSTEM_ALERT_WINDOW permission denied!');
                  return;
                }
              }

              if (!(await Permission.ignoreBatteryOptimizations.isGranted)) {
                bool requested = await Permission.ignoreBatteryOptimizations
                    .request()
                    .isGranted;
                if (!requested) {
                  debugPrint('IGNORE_BATTERY_OPTIMIZATION permission denied!');
                  return;
                }
              }
```
2. Connect iOS device or simulator & flutter run.
3. Press + icon to add new alarm.
4. Press Save button.
5. Press Grant Permissions button.
6. Alarm is setup but code output in terminal is: 
```
Notification permission denied!
```
7. Also causes the similar UI issue of navigating back as mentioned in #497 (does not navigate back to home screen after alarm is setup)

It does not asks for notification permissions because these are not setup properly for IOS.

- I am setting up the permissions according to [these instructions](https://github.com/Baseflow/flutter-permission-handler/issues/1114#issuecomment-1649425295) mentioned in one of the issues in the official Github repo of permissions_handler plugin.

**Comment by MarkisDev** [comment]
Merged with #499
