### ISSUE TITLE
Bug: Label Text with whitespace doesn't show "Off" and stays empty

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#51]
### Description

The Label Text in the "Add or Update Alarm View" shows off when the user doesn't enter anything in the text field. But it's not showing off when the user enters a whitespace or some whitespaces. There is no text present there, so it should show Off. 

I'm attaching the screen recording of the mentioned issue. If possible, please assign me this issue. 

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/5d3d243d-87e0-440e-80dd-5bbbededef16

**Comment by MarkisDev** [comment]
I've assigned this to you
