### ISSUE TITLE
Bug: Timer Number Picker isn't updating the timer text field.

### ISSUE THREAD

**Issue by AmrAbdElHamed26** [CCExtractor/ultimate_alarm_clock#516]
### Description

Changing the numbers in the **number picker** for hours, minutes, and seconds **doesn't update the values** in **the timer text field.**

https://github.com/CCExtractor/ultimate_alarm_clock/assets/86882938/027f8799-fc9a-412a-85cf-7b6cbc8695a4

**Comment by MarkisDev** [comment]
Merged with #521
