### ISSUE TITLE
Bug:  The '+' Floating Action Button does not allow user to add more Alarms just after adding an Alarm

### ISSUE THREAD

**Issue by fierychicken65** [CCExtractor/ultimate_alarm_clock#546]
### Description

Clicking on the + button allows you to save an alarm the first time. When user clicks on + button just after saving an alarm he is not able to create another alarm (User only gets option to update the existing Alarm he had just saved).
User needs to refresh page in order to save another Alarm. 
Clicking on an existing alarm (after refreshing the home page) and updating it's values creates a new alarm instead of updating the chosen Alarm.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/116811583/c44d1bd7-599b-4f0f-89a9-f0d52daf9fe4

**Comment by AryanSarafDev** [comment]
The controllers in the add screen need resetting too
