### ISSUE TITLE
Bug: An alarm - that is not set by user - rings after device is powered on (and unlocked).

### ISSUE THREAD

**Issue by Detective-Khalifah** [CCExtractor/ultimate_alarm_clock#548]
### Description

Whenever the device is restarted or powered on, an alarm that has not been set by the user rings.
This ringing occurs even when there are 0 active alarms on the app.
It seems to happen due to [AlarmReceiver.kt](https://github.com/CCExtractor/ultimate_alarm_clock/blob/main/android/app/src/main/kotlin/com/example/ultimate_alarm_clock/AlarmReceiver.kt) being triggered - after boot is complete - by the [`BroadcastReceiver`](https://developer.android.com/reference/android/content/BroadcastReceiver) in the [AndroidManifext.xml](https://github.com/CCExtractor/ultimate_alarm_clock/blob/f7f68c6bf7a6166c5151819a1b8975db173d34e3/android/app/src/main/AndroidManifest.xml#L35) file.

Further testing needed to verify this behaviour on devices that do not support [direct boot](https://developer.android.com/privacy-and-security/direct-boot/).

Further read:
- https://developer.android.com/develop/background-work/background-tasks/broadcasts
- https://developer.android.com/reference/android/content/BroadcastReceiver

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/58272349/aaf8ac5c-cbc3-4f85-973f-3c0670e5cfb9

**Comment by AryanSarafDev** [comment]
I have fixed the issue in Issue number #562 @Detective-Khalifah @MarkisDev

**Comment by Detective-Khalifah** [comment]
I will check it and give you feedback-------- Original message --------From: AryanSarafDev ***@***.***>Date: Fri, 26 Apr 2024, 02:20To: CCExtractor/ultimate_alarm_clock ***@***.***>Cc: Detective_Khalifah ***@***.***>, Mention ***@***.***>Subject: Re: [CCExtractor/ultimate_alarm_clock] Bug: An alarm - that is not set by user - rings after device is powered on (and unlocked). (Issue #548)
I have fixed the issue in Issue number #562 @Detective-Khalifah @MarkisDev

**Comment by Detective-Khalifah** [comment]
I think the issue is resolved -- unset alarm no longer rings after boot, @AryanSarafDev.

cc: @MarkisDev
