### ISSUE TITLE
Bug: Alarm Not Deleting After Enabling "deleteAfterGoesOff"

### ISSUE THREAD

**Issue by keyurgit45** [CCExtractor/ultimate_alarm_clock#550]
### Description

Steps to reproduce the issue:
1. create an alarm with the `deleteAfterGoesOff` option enabled.
2. Let the alarm Ring
3. After alarm dismissal, the same alarm will be in the alarm list.

The code for `deleteAfterGoesOff` is written in AlarmRingController's `onInit()` function. When the code is triggering, `currentlyRingingAlarm` holds the FakeAlarmModel value instead of the actual ringing alarm value. That's why the delete operation is not being performed.

Solution:
I will add the code in the `onTap()` function of the Dismiss button. So when the user dismisses the alarm, the alarm will be deleted.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/75253653/321a8958-dc9f-4775-b4ed-cb77708754c3

**Comment by vkprogrammer-001** [comment]
can i work on this issue
