### ISSUE TITLE
Styling: Making Settings Page Consistent

### ISSUE THREAD

**Issue by duckcommit** [CCExtractor/ultimate_alarm_clock#553]
### Description

The undo setting text is not consistent with the rest of the buttons.

### Screenshots

![Screenshot_20240414_235626](https://github.com/CCExtractor/ultimate_alarm_clock/assets/22213675/c2892912-740d-44e9-8d77-b05191eb8632)

**Comment by Gaurav-Kushwaha-1225** [comment]
Hey @duckcommit, please close this issue as it is resolved.
