### ISSUE TITLE
Styling: The Apply Duration text is not in contrast

### ISSUE THREAD

**Issue by duckcommit** [CCExtractor/ultimate_alarm_clock#559]
### Description

All the other buttons in the entire app follow a black color with green background. Same style is not found in the undo duration set button.

### Screenshots

![Screenshot_20240415_003446](https://github.com/CCExtractor/ultimate_alarm_clock/assets/22213675/258ca88b-07fa-4a11-918d-c62153b06d73)

**Comment by Abhinav232004** [comment]
@AryanSarafDev ,Can you please assign this to me?

**Comment by khush1yaaar** [comment]
I am a proficient flutter developer, new to open source. please assign me this issue.
