### ISSUE TITLE
Feature: Implement SliverAppBar on HomePage

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#56]
### Description

When we have added enough alarms on the `Home Page` to make it scrollable, the `AppBar` still stays there on the top. We can use `SliverAppBar` widget so that on scrolling it, the `AppBar` gets hidden, and on scrolling it up, it shows up. It will surely enhance the user experience. Because the user will get more space to get a look at his/her alarms. 

If possible, please assign me this issue. 

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/2dab3a2e-2750-4a8a-a3c8-910105965558

**Comment by MarkisDev** [comment]
I honestly intended the design to be like this. I think knowing the duration of the next alarm seemed nicer, but I also understand your take on this. 

How about we make a sticky app bar that reduces its size when we scroll?

**Comment by MarkisDev** [comment]
Yup, you can ignore the settings icon for now. I'll make a drawer and replace the settings page with the drawer.

**Comment by superiorsd10** [comment]
@MarkisDev So won't the size of settings icon be affected on scrolling?

**Comment by MarkisDev** [comment]
Hmm, we can hide it when scrolling? As you scroll, we can change text size and the total space occupied by the app bar making it sticky.

However, when you scroll back to the top, it should go back to how it is right now. 

I think that will look great!

**Comment by superiorsd10** [comment]
@MarkisDev Okay! I'll try to implement it. Yes, I think it will look great.
