### ISSUE TITLE
Bug : Render Overflow

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#57]
### Description

The newly added feature have an overflow issue when label size if big 
I am attaching a screenshot

### Screenshots

<img width="326" alt="image" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/11013071-adba-4042-b1b0-c02cd2a85e38">

**Comment by MarkisDev** [comment]
I've assigned this to you.
