### ISSUE TITLE
Bug: Dark theme not working properly

### ISSUE THREAD

**Issue by Gaurav-Kushwaha-1225** [CCExtractor/ultimate_alarm_clock#576]
### Description

On the Timer Page while adding timer dark theme toggle button is not working properly. 
Can you please assign this issue to me??

### Screenshots

![photo_2024-06-19_01-00-43](https://github.com/CCExtractor/ultimate_alarm_clock/assets/117214772/9359e052-7302-4030-a880-c118ebef0ddf)

**Comment by AryanSarafDev** [comment]
Hi! Instead of using the current method for theming, you can try improving the complete theme switching with something like [this](https://medium.com/@rushitokapure/exploring-themes-in-flutter-using-getx-315b78faa643).
