### ISSUE TITLE
Left operand can't be null issue

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#6]
Issue :
<img width="946" alt="Screenshot 2023-06-17 at 11 16 55 PM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/82240da7-6c19-498e-9a3a-e4b28baeb150">

The issue is solved by #5 please check it out and give review

**Comment by BrawlerXull** [comment]
@MarkisDev @cfsmp3 @NishantSinghal19

**Comment by BrawlerXull** [comment]
Hey!! is there something wrong with the pr @MarkisDev ?

**Comment by MarkisDev** [comment]
Working on fixing a bug with this function, would have to put it on hold until I finish that :)

I invite you explore the codebase and put up more valuable issues like these!

**Comment by BrawlerXull** [comment]
Currently I am having an error to run it locally

All i am seeing is a white screen when I am trying to run in my mac

**Comment by BrawlerXull** [comment]
> Working on fixing a bug with this function, would have to put it on hold until I finish that :)
> 
> I invite you explore the codebase and put up more valuable issues like these!

What is the bug is there something I may contribute?

**Comment by MarkisDev** [comment]
> Currently I am having an error to run it locally
> 
> All i am seeing is a white screen when I am trying to run in my mac

Are you running this on Android? I am not currently working on iOS devices

**Comment by BrawlerXull** [comment]
> > Currently I am having an error to run it locally
> > All i am seeing is a white screen when I am trying to run in my mac
> 
> Are you running this on Android? I am not currently working on iOS devices

Yeah I am running this on IOS
I guess it is some plist file issue

**Comment by MarkisDev** [comment]
If you figure a fix, a PR would be much appreciated :)

> > > Currently I am having an error to run it locally
> > > All i am seeing is a white screen when I am trying to run in my mac
> > 
> > 
> > Are you running this on Android? I am not currently working on iOS devices
> 
> Yeah I am running this on IOS I guess it is some plist file issue

**Comment by BrawlerXull** [comment]
> If you figure a fix, a PR would be much appreciated :)
> 
> > > > Currently I am having an error to run it locally
> > > > All i am seeing is a white screen when I am trying to run in my mac
> > > 
> > > 
> > > Are you running this on Android? I am not currently working on iOS devices
> > 
> > 
> > Yeah I am running this on IOS I guess it is some plist file issue

YEAH

**Comment by MarkisDev** [comment]
> > Working on fixing a bug with this function, would have to put it on hold until I finish that :)
> > I invite you explore the codebase and put up more valuable issues like these!
> 
> What is the bug is there something I may contribute?

I'd honestly like to work on this one - it has to do with shared alarms not showing up with the remaining.

But I'm sure we can find issues if we test the application, feel free to give it a go!

**Comment by BrawlerXull** [comment]
I'll first resolve this white screen issue then I'll go forward to the bug you are talking about 
Can you please cross check if your pc is also showing the same white screen issue when we try to run it on ios simulator

**Comment by BrawlerXull** [comment]
<img width="752" alt="Screenshot 2023-06-18 at 12 43 27 AM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/ce7fabc5-ce94-4391-8451-d9ec48b030ba">
Also I am getting such logs when I am trying to run it
I haven't yet tried to run it on android emulator I'll fix this for sure after my exams ends currently busy doing college stuff

**Comment by MarkisDev** [comment]
Unfortunately, I am unable to test for iOS. Would need help with this.

Let's move the discussion to #7

**Comment by MarkisDev** [comment]
I'm going to close this since I've changed the latestAlarms function to include shared alarms as well.
