### ISSUE TITLE
Feature: Delete Alarm(Text) Button Color Should be Red

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#60]
### Description

I believe that anything(particularly talking about set alarms) that can be discarded or deleted should have a red text button.

Before:- 
![21](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/15a14d81-8b02-460a-b600-6232547a378a)

After:-
![23](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/cea9dfc2-4f92-4890-9a56-8b4605c8268e)

**Comment by MarkisDev** [comment]
I agree. I'll merge this in, thanks :)
