### ISSUE TITLE
Feature: Change the design of API Key Default Dialog

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#63]
### Description

Currently, the design of the **API Key Default Dialog** looks good, but I see a problem there. The `GetKey` button looks like it's disabled, and the user feels that nothing is gonna happen on pressing it. So I think we should change its design. 

**Current Design**
<a href="https://ibb.co/NWtD7v0"><img src="https://i.ibb.co/P1FXtL2/Whats-App-Image-2023-09-07-at-2-59-39-PM.jpg" alt="Whats-App-Image-2023-09-07-at-2-59-39-PM" border="0" width="300" height="200"></a>

**Proposed Design**
![api-key-box-design](https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/accafad1-4487-4f60-8cf5-3ac45a3ff162)

**Comment by MarkisDev** [comment]
Ah, I definitely agree with this. I couldn't come up with a better design for the button, thanks! :)

**Comment by superiorsd10** [comment]
@MarkisDev No worries! I'll be working on it today :)
