### ISSUE TITLE
Bug: Alarm Tile is showing | on entering whitespace in Label Text

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#65]
### Description

When the user enters one or more whitespace in the `Label Text`, the `Alarm Tile` still shows `|`.

### Expected Behaviour
The `Alarm Tile` shouldn't show the `|` when the user enters one or more whitespace(only) in the `Label Text`. 

### Screenshots

<a href="https://ibb.co/dptKp6g"><img src="https://i.ibb.co/4S2NSMd/SCR-20230908-mxy.png" alt="SCR-20230908-mxy" border="0" width="250" height="500"></a>

**Comment by MarkisDev** [comment]
I've assigned this to you

**Comment by kundankumaryadav88** [comment]
i can fix this can you assign me this
