### ISSUE TITLE
Feature: Showing a snackbar when the user enters whitespace first in the Label Tile

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#68]
### Description

When the user enters a whitespace first in the `Label Tile`, nothing really happens, and the `hintText` doesn't disappear. So I'm thinking of showing a `snackBar` when the user enters a whitespace first in the `Label Tile` to enhance the user experience. 

If possible, please assign me this issue. 

### Screenshots
<a href="https://ibb.co/Yd6RfY0"><img src="https://i.ibb.co/fNb1rBD/SCR-20230914-qf0.png" alt="SCR-20230914-qf0" border="0" height="550" width="250"></a>

**Comment by MarkisDev** [comment]
I'll assign this to you. Could you please also add screenshots to this issue?

**Comment by superiorsd10** [comment]
> I'll assign this to you. Could you please also add screenshots to this issue?

Sure :)

**Comment by superiorsd10** [comment]
@MarkisDev Hey! So should I use the Get.snackbar still?
