### ISSUE TITLE
Blank white screen when trying to open app in iOS Simulator

### ISSUE THREAD

**Issue by BrawlerXull** [CCExtractor/ultimate_alarm_clock#7]
This is a firebase configuration issue 
<img width="752" alt="Screenshot 2023-06-18 at 12 43 27 AM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/4a2146d0-9d90-420f-b2cf-8e8d8cf769c7">

Do let me know if anyone have solution for this

![simulator_screenshot_6861C32E-9C60-4111-87AA-F7D14F75B3A7](https://github.com/CCExtractor/ultimate_alarm_clock/assets/111864031/9ae03eb5-4620-45d4-b303-1608a197e4b1)

**Comment by BrawlerXull** [comment]
This is a firebase issue which can be solved by the one who has configured the files for android version of the application as it is not downloadable by any other user other than the one who have created the firebase project

**Comment by BrawlerXull** [comment]
@MarkisDev if you are able to download and share the firebase iOS configuration file from https://console.firebase.google.com/ 
I'll be solving this issue with no ease

**Comment by MarkisDev** [comment]
Will look into it shortly.

**Comment by BrawlerXull** [comment]
Please download googleservice-info.plist file and share me on slack/github @MarkisDev

**Comment by BrawlerXull** [comment]
> Please download googleservice-info.plist file and share me on slack/github @MarkisDev

I'll fix it ASAP

**Comment by MarkisDev** [comment]
I've sent you the file over at slack - I haven't setup the SDK for iOS. You might have to do that as well.

I've assigned this issue to you :)

**Comment by BrawlerXull** [comment]
I'll be solving this issue after 1 week let my exams end then I'll look into this :)

**Comment by BrawlerXull** [comment]
> I've sent you the file over at slack - I haven't setup the SDK for iOS. You might have to do that as well.
> 
> I've assigned this issue to you :)

check #17 @MarkisDev
