### ISSUE TITLE
Feature: Add Light Mode

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#71]
### Description

I'm thinking of implementing the light mode in this app. The current theme data corresponds to the dark mode of the app but it's necessary that we give users a preference to opt for light mode as well. So I'll be defining another theme data corresponding to the light mode of the app. To give the user a choice, I'll be making a switch tile in the settings of the app similar to haptic feedback and the sorted alarm list.

If possible, please assign me this issue.  

### Screenshots

<a href="https://ibb.co/KDQRJF0"><img src="https://i.ibb.co/pQsGSJ0/SCR-20230916-1qn.png" alt="SCR-20230916-1qn" border="0" width="250" height="550"></a>

**Comment by MarkisDev** [comment]
Sounds like a great idea! I'll assign this to you :)
