### ISSUE TITLE
Feature: Change the Switch Color

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#72]
### Description

The current switch color _(when turned on)_ doesn't really match the theme of the app. So I think it can be changed to something that aligns with the current theme of the app. 

If possible, please assign me this issue.

### Before

<a href="https://ibb.co/nz44PK0"><img src="https://i.ibb.co/9sBBZdv/SCR-20230916-1x3.png" alt="SCR-20230916-1x3" border="0" width="250" height="550"></a>

### After

<a href="https://ibb.co/g3s2Dx6"><img src="https://i.ibb.co/PNBL5dt/SCR-20230916-1x8.png" alt="SCR-20230916-1x8" border="0" width="250" height="550"></a>

**Comment by MarkisDev** [comment]
I understand your POV, but I was hoping to have a primary color and a secondary color for the app to sort of make a color pallette. Do you think we could use secondary somewhere else?

**Comment by superiorsd10** [comment]
@MarkisDev I don't think that there is any element (button, switch, radio) where we can use the current color (switch). I suggested it because I think it's nice to have a single color for all buttons, switch, radio, etc.

**Comment by MarkisDev** [comment]
Hmm, I think I prefer the secondary color since we can reuse it somewhere else later on.

**Comment by superiorsd10** [comment]
> Hmm, I think I prefer the secondary color since we can reuse it somewhere else later on.

Okay, sounds good :)

Btw can we please discuss the light-dark mode on Slack?
