### ISSUE TITLE
Feature: Restrict Landscape Mode

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#75]
### Description

I think we should restrict the landscape mode in this app. Because when the phone is rotated, the app transitions to landscape mode, and the UI kind of disrupts. The text inside the button disappears, the height of the tile becomes smaller, and many more. So it'll be better to restrict the landscape mode in this app. After all, it's an alarm application so I think there is no need for landscape mode for it. 

if possible, please assign me this issue. 

### Screenshots

_Please open this image for a better view._

<a href="https://ibb.co/PcCb8cW"><img src="https://i.ibb.co/PcCb8cW/Whats-App-Image-2023-09-24-at-3-03-19-PM.jpg" alt="Whats-App-Image-2023-09-24-at-3-03-19-PM" border="0"></a>

**Comment by MarkisDev** [comment]
Yeah that makes sense. I agree it should be locked to potrait.
