### ISSUE TITLE
Feature: Add App Icon for iOS

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#76]
### Description

Currently, the application doesn't have an app icon for iOS devices. So we should add an app icon for iOS devices just like Android. 

My suggestion is to use [flutter_launcher_icons](https://pub.dev/packages/flutter_launcher_icons) to implement this. We can have icons for both platforms using this package.

If possible, please assign me this issue. 

### Screenshots

_Please open this image for a better view_

<a href="https://ibb.co/sKFf1P1"><img src="https://i.ibb.co/sKFf1P1/Simulator-Screenshot-i-Phone-14-Pro-2023-09-24-at-15-21-06.png" alt="Simulator-Screenshot-i-Phone-14-Pro-2023-09-24-at-15-21-06" border="0"></a>

**Comment by MarkisDev** [comment]
Ahhh, I think I did use it to generate android icons. I'm not able to test for iOS, so couldn't do it. I'll assign this to you as well.
