### ISSUE TITLE
Feature: Update the OpenWeatherMap API Key

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#80]
### Description

Currently if the `Open Weather Map API Key` is not added, the app displays a `defaultDialog` to save the key. Once it is saved, a successful confirmation message is shown to the users. 

Once the user has added an API key, if they again tap on the Open Weather Map API Tile, they are shown a successful confirmation message. I think instead of this, we should let them update the API key. Because the API key can be deactivated, and deleted. So the user will not be able to use the features utilizing the API key once it happens. 

If the user has already added the API key, we should show them a `defaultDialog` to update the key. 

If possible, please assign me this issue. 

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/0beee5fa-c953-4c2c-95d8-93dee95300e9

**Comment by superiorsd10** [comment]
@MarkisDev Ya got it. You're right, it'll be confusing for them for sure. 

So if the user has already added an API key, then maybe we can show them a dialog, and it's structure will be:-

```
Your API Key

Text(API Key)

Row of two buttons [Update API Key & Cancel]
```

On tapping Update API Key button, we can show another dialog, and it's structure will look like:-

```
Update API Key

TextField

Row of two buttons [Save & Cancel]
```

Please let me know if there are any changes required to this. I'll start working on this PR once you approve it. 

Thank you :)

**Comment by MarkisDev** [comment]
Yeah this sounds like a better approach. Please go ahead and please let me know if you get stuck somewhere :)

**Comment by superiorsd10** [comment]
Ya, sure! Thanks :)

**Comment by superiorsd10** [comment]
@MarkisDev Hello 👋

Don't you think that the `Your API Key` dialog does not serve any purpose, and is redundant? Because, if the `apiKey` is already added, then when the user taps on the tile, we can show them the `Update API Key` dialog, in which `apiKey` will already be present in the text field of the `apiKey`, and they can update it then.

**Comment by MarkisDev** [comment]
That's also fine, it's not as confusing.

**Comment by superiorsd10** [comment]
Hey @MarkisDev 👋
Actually, I'm facing a small issue while implementing this. When the user clicks on the tile to add their API key, the dialog shows up. Once they enter it, and click on Save, the `Your API Key is added` dialog shows up. Now, when the user clicks `Okay` there, the first dialog is also shown for some milliseconds. The same is the case for `Update Key` as well. 

I'm uploading a screen recording for better understanding. Please help me to resolve it. 

https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/19c423d9-8937-44a2-b48e-08525ce605ee

**Comment by MarkisDev** [comment]
@superiorsd10 have you tried using Get.back() to close the first dialog before creating a new one?

**Comment by superiorsd10** [comment]
> @superiorsd10 have you tried using Get.back() to close the first dialog before creating a new one?

No, but we aren't creating a new dialog, we're just updating the content of the first one based on the state.

**Comment by superiorsd10** [comment]
Okay! @MarkisDev

**Comment by superiorsd10** [comment]
Hey 👋 @MarkisDev,

I've made a PR for this issue. Still, there are some workarounds to be done. So I'll be creating another issue to resolve them. Because I feel that they're really important for the functionality of this feature, it's better to separate them.
