### ISSUE TITLE
Feature: Show Dialog when user press back button on Add or Update Alarm View

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#82]
### Description

Currently, when the user presses the back button on their device or on the AppBar when they are `Add or Update Alarm View`, the app redirects them to `Home View`. Users may press the back button by mistake, and this will result in the loss of all the saved data at that instance. 

My suggestion is to show a dialog whenever users press the back button, and the structure of this dialog will be:-

```
Title: Discard Changes?

Message: You have unsaved changes. Are you sure you want to leave this page?

Actions: 

    1. Discard: It lets the user confirm that they want to leave this page and discard any unsaved changes. 
    2. Cancel: It allows the user to stay on this page, and lets them edit their alarm. 
```

If possible, please assign me this issue. 

### Screenshots

<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/4e42042a-c2eb-4c35-a41e-ae5188bf3bd0" width="400" height="300">

**Comment by MarkisDev** [comment]
Yeah, this does make sense. I'll assign this to you :)
