### ISSUE TITLE
(Enable Light Mode) Switch button Active Color should be same as (Enable Haptic Feedback and Enable Sorted Alarm List's) Switch button.

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#84]
### Description

In the setting option, the Enable Light Mode Switch button color Looks Odd.
I think we should go with the Switch button color of Haptic feedback and Sorted Alarm List which is (ksecondaryColor).
If possible Assign this issue to me.

Present:-

![Screenshot_20230927_111858](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/995ccca2-7f03-4f3c-9b71-9f728321cf08)

After:-
![Screenshot_20230927_112149](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/3bde74bd-3253-4cbb-a835-90eff9e7b78e)

**Comment by tavkeer** [comment]
can i work on this

**Comment by itsgits01** [comment]
Hey can I help to resolve this???

**Comment by MarkisDev** [comment]
I've assigned this to you @sameermansoori1
