### ISSUE TITLE
Feature: Select Multiple Alarms to Delete on Holding an Alarm

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#86]
### Description

Currently, it's good to have a `Delete alarm` feature in the app. But what if the user wants to delete multiple alarms at once? Then he/she will have to tap the pop-up menu buttons individually for the alarms and delete alarms individually. 

My suggestion is to implement the select multiple alarms at once feature. With this feature, a user will be able to select multiple alarms at once and delete them. To multi-select alarms, the user will need to long-press any alarm tile. 

Currently, the HomePage's rough structure looks like this:-

```
AppBar [Next Alarm                    Settings Icon]

List of Alarms
```

The AlarmCard's rough structure looks like this:- (it's an example)

```
One-Time                                Switch Button

10:36 AM                                Pop-up Menu Button
```

On long-pressing any alarm, both should change to:-

```
AppBar [X (to get back to original view)    Select Item (if none of the alarms are selected)                Radio Button (to select all the alarms)      Delete Icon (to delete the selected alarms)]

List of Alarms
```

```
One-Time
                                                Radio Button (to select this particular alarm)
10:36 AM
```

If possible, please assign me this issue.

**Comment by MarkisDev** [comment]
Yeah, I do think we need this. I'll assign this to you.

**Comment by superiorsd10** [comment]
Hey @MarkisDev 👋
Sorry for bothering you. But I've been stuck on this problem since yesterday afternoon. After multiple attempts, I'm not able to resolve the problem. So please can you please me with this? 

As you can see, on long-pressing, the height of the card reduces. It should stay the same. I tried many things, but it didn't work out. 


https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/c342288a-2b17-446b-8278-60ebaeb22eba

**Comment by ykhan2476** [comment]
If possible, please assign me this issue.

**Comment by superiorsd10** [comment]
> Hey @MarkisDev 👋 Sorry for bothering you. But I've been stuck on this problem since yesterday afternoon. After multiple attempts, I'm not able to resolve the problem. So please can you please me with this?
> 
> As you can see, on long-pressing, the height of the card reduces. It should stay the same. I tried many things, but it didn't work out.
> 
>  Screen.Recording.2023-09-30.at.12.11.58.PM.mov

Hello @MarkisDev 👋
I've resolved the above-mentioned issue that I was facing. I've used conditional padding to resolve it. I'll be making the PR for this issue soon. 

Thank you,

**Comment by MarkisDev** [comment]
Hey @superiorsd10

Sounds great, sorry about the late reply, I was travelling :)

Feel free to put up a PR!

**Comment by superiorsd10** [comment]
> Hey @superiorsd10
> 
> Sounds great, sorry about the late reply, I was travelling :)
> 
> Feel free to put up a PR!

Hello @MarkisDev 👋
It's absolutely fine! I've made a PR recently. Please look into it. 

Thank you :)
