### ISSUE TITLE
Bug: Bottom Overflow Error on Settings View

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#87]
### Description

On Settings View, when we tap on the `Weather API Key` tile to add the API key, the bottom overflow error shows up. 

if possible, please assign me this issue. 

### Screenshots

<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/2a8cb0b9-e191-4174-8583-6673aa04e402" height="550" width="250">

**Comment by GOUTHAM-2002** [comment]
Hey , i fixed the issue

**Comment by MarkisDev** [comment]
Feel free to put up a PR @GOUTHAM-2002

**Comment by GOUTHAM-2002** [comment]
okay

**Comment by GOUTHAM-2002** [comment]
hey , i raised the pull request , this is my first time contributing to an open source , sorry if i make any mistakes

**Comment by oiiakm** [comment]
Hey @MarkisDev  can I work on this issue

**Comment by MarkisDev** [comment]
It's been fixed with #88
