### ISSUE TITLE
In the (Add or Update Alarm View) when the user press back button, the dialog (Discard Changes) had a Green color (Leave button).

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#89]
### Description

I think it should be Red which gives the user a better Experience.
Please assign this issue to me.

Attaching some Screenshots of the present and after the implementation, have a look

### Screenshots

Present-
![Screenshot_20230928_173737](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/0fe0fdea-4c61-4cd3-8c7a-168fb10e3b38)
![Screenshot_20230928_173822](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/263fa7fb-101f-4233-9d24-9d77d26152a4)

After-
![Screenshot_20230928_173545](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/f9a2c38e-18cc-4efc-9287-ea6a499a62bd)
![Screenshot_20230928_173639](https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/7cdaff04-0b29-4f00-bb01-fbf5d2d354b5)

**Comment by Roshaen** [comment]
I would like to work on this.
Can you assign this issue to me @sameermansoori1 ?

**Comment by MarkisDev** [comment]
I've assigned this to you @sameermansoori1

**Comment by priyanshu2384** [comment]
I would like to work on this issue. Can you assign it to me @priyanshu2384?
