### ISSUE TITLE
Bug: API Key and Weather Key State not loaded in the SettingsController

### ISSUE THREAD

**Issue by superiorsd10** [CCExtractor/ultimate_alarm_clock#91]
### Description

**API Key**

On saving or updating the API Key, it's being stored in the local storage. But when the app is hot restarted, and the user has already added the key before and wants to update it, the `apiKey TextEditingController` restarts and all the data inside it is gone. This way the user will get confused whether their API Key is still there or not. 

So I think we should create a variable, and should store the latest API Key there. This way, we can show the latest API key to the user without any hassle. 

**Weather Key State**

It plays a key role in showing the content of the dialog. But we aren't storing it in the local storage. Therefore when the app restarts, it again gets assigned to the `add` state. So the user will see the `Add` button in the dialog instead of `Update` when they want to update the API Key later. 

So we can store it in the local storage, and retrieve it whenever the `SettingsController` is created. 

_I would like to work on this issue, so please assign it to me._

**Comment by MarkisDev** [comment]
Ah, sounds about right. Please go ahead with it. Let me know if you get stuck somewhere :)

**Comment by superiorsd10** [comment]
Hello @MarkisDev 👋
What's the status of this [PR](https://github.com/CCExtractor/ultimate_alarm_clock/pull/90)? 

Because this issue depends on this PR. So I'll start to work on this as soon as you approve this PR. 

Thank you,

**Comment by MarkisDev** [comment]
@superiorsd10 Yup, once again sorry about the delay!

I've merged #90, feel free to let me know if you face any other issue :)

**Comment by superiorsd10** [comment]
> @superiorsd10 Yup, once again sorry about the delay!
> 
> I've merged #90, feel free to let me know if you face any other issue :)

It's absolutely fine! I understand. 
Thanks for merging the PR. I'll be working on it now.

Thank you :)
