### ISSUE TITLE
In the label tile the snackbar (background and text color)does not change when dark mode is enabled it is showing the same in both mode.

### ISSUE THREAD

**Issue by sameermansoori1** [CCExtractor/ultimate_alarm_clock#93]
### Description

When we enabled dark mode, In the label tile when the user entered whitespace first the snackbar had a white background and black text color which does not go with the dark mode theme.

Could you assign this issue to me?

Present-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/926f14f1-0513-43f8-8305-598ce7a1a715

After-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/bf7ce124-21b5-4079-b7f5-96ae0e20f8a5

**Comment by ykhan2476** [comment]
If possible, please assign me this issue.

**Comment by MarkisDev** [comment]
Hmmm, I'm not sure about this one. Now that I think about light and dark theme, I think all alert/error snackbars should be the same color to avoid confusion.

Like, red for error makes sense on both themes.

**Comment by sameermansoori1** [comment]
> Hmmm, I'm not sure about this one. Now that I think about light and dark theme, I think all alert/error snackbars should be the same color to avoid confusion.
> 
> Like, red for error makes sense on both themes.

okay, I will do that.

**Comment by sameermansoori1** [comment]
> Hmmm, I'm not sure about this one. Now that I think about light and dark theme, I think all alert/error snackbars should be the same color to avoid confusion.
> 
> Like, red for error makes sense on both themes.

Okay, I will do that.

**Comment by sameermansoori1** [comment]
Have a look. @MarkisDev 


https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/e3b587a4-a506-40cc-b93c-98e46fb02e32

**Comment by sameermansoori1** [comment]
> Hmm, don't you think a better idea would be to have a red bg color with white text for both the themes for all errors and green bg color for all "success" notifications?


https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/d26f6151-cb43-4185-8e15-537638c0b889

You are right, it looks better now....

**Comment by MarkisDev** [comment]
Assigning to you @sameermansoori1
