### ISSUE TITLE
The Status bar color is kind of odd and that must be transparent or any other

### ISSUE THREAD

**Issue by tavkeer** [CCExtractor/ultimate_alarm_clock#94]
### Description

The Status bar color is kind of add and that must be transparent or any other

### Screenshots

![Screenshot_1696262021](https://github.com/CCExtractor/ultimate_alarm_clock/assets/105163810/9c1ef890-5366-43d6-b952-3872b0781f3a)

**Comment by tavkeer** [comment]
please assign this to me

**Comment by tavkeer** [comment]
i have fixed it should i make a PR

**Comment by tavkeer** [comment]
hey i have made a PR can you have a look

**Comment by ykhan2476** [comment]
If possible, please assign me this issue.

**Comment by MarkisDev** [comment]
Could you elaborate on what you're trying to do here? I didn't quite understand.

Do you mean the status bar (grey color) isn't looking good? 

Would be helpful if you could put screenshots of your proposed changes as well :)

**Comment by tavkeer** [comment]
Yeah the status bar grey colour is not looking good so I made the change regarding that

**Comment by tavkeer** [comment]
here is the final product

**Comment by MarkisDev** [comment]
Merged with #95

**Comment by tavkeer** [comment]
Thanks
